// WebGLEngine/render/cloudField.js — v4055
// ---------------------------------------------------------------------------------------------------------------
// WHERE THE PUFFS GO. Pure arithmetic: a type name and a seed in, an array of {x,y,z,w,h,colTop,colBot,density}
// out. No GL, no DOM, no Three -- which is what lets two completely different renderers draw the SAME clouds,
// and lets the placement be pinned by an answer key instead of eyeballed.
//
// Keith: "we also have great clouds we made to pass through." They ARE great, and they were also unreachable:
// render/cloudLayer.js is raw WebGL2 with its own shader program and its own inline puff generator, so the
// Three.js planet page could not use them without a second copy of the placement logic. This file is the half
// that ports. cloudLayer.js keeps its WebGL2 drawing and now imports its puffs from here, so the engine's sky
// and the planet's sky are generated by one function rather than by two that started identical.
//
// *** AND THE EXTRACTION FIXED SOMETHING THE ORIGINAL COULD NOT DO: IT IS SEEDED. *** regenerate() called
// Math.random() directly, so the same cloud field could never be rebuilt twice -- which meant no gate could
// assert anything about a specific field, only about ranges. Placement now runs on mulberry32 (the SAME
// deterministic PRNG world/procPlanet.js seeds planets with, integer math only, stable across machines), so a
// seed names a sky. The engine passes a fresh seed per regenerate, so nothing about its behaviour changes.
//
// WHAT PORTS AND WHAT DOES NOT, STATED RATHER THAN ASSUMED: a type's CHARACTER ports -- puff counts, the
// width/height ranges, the tower stacking, the two-tone colours, the density. Its ABSOLUTE ALTITUDE does not:
// TYPES.cumulus sits at y=135 in an engine world whose terrain is tens of units tall, and dropping that number
// onto a planet of radius 17 would put the weather eight radii out in space. So the shell builder takes the
// altitude and a size scale from its CALLER, who is the only one who knows how big the world is.
// ---------------------------------------------------------------------------------------------------------------
"use strict";

import { rng } from "../world/procPlanet.js";   // mulberry32 -- one seeded PRNG for the whole tree

// Six meteorological types, each with its own altitude band, shape, coverage and shading. Moved here from
// render/cloudLayer.js at v4055 so the generator and the table live together; cloudLayer imports them back.
const TYPES = {
    cumulus:       { altitude: 135, clouds: 9,  puffs: [4, 7], w: [34, 60], h: [26, 44], spreadXZ: 55, spreadY: 14, colTop: [1.0, 1.0, 1.0],  colBot: [0.80, 0.83, 0.90], density: 0.95 },
    cumulonimbus:  { altitude: 110, clouds: 3,  puffs: [9, 14], w: [55, 95], h: [55, 120], spreadXZ: 60, spreadY: 90, tower: true, colTop: [1.0, 1.0, 1.0], colBot: [0.40, 0.42, 0.50], density: 1.0 },
    stratus:       { altitude: 90,  clouds: 14, puffs: [3, 5], w: [90, 150], h: [22, 34], spreadXZ: 120, spreadY: 8, colTop: [0.82, 0.84, 0.88], colBot: [0.70, 0.72, 0.78], density: 0.8 },
    stratocumulus: { altitude: 105, clouds: 12, puffs: [4, 6], w: [55, 90], h: [30, 46], spreadXZ: 90, spreadY: 12, colTop: [0.92, 0.93, 0.96], colBot: [0.72, 0.75, 0.82], density: 0.88 },
    cirrus:        { altitude: 235, clouds: 11, puffs: [3, 5], w: [80, 140], h: [8, 16], spreadXZ: 110, spreadY: 18, colTop: [1.0, 1.0, 1.0], colBot: [0.95, 0.97, 1.0], density: 0.5 },
    nimbostratus:  { altitude: 85,  clouds: 13, puffs: [4, 6], w: [95, 160], h: [24, 38], spreadXZ: 120, spreadY: 8, colTop: [0.62, 0.64, 0.70], colBot: [0.48, 0.50, 0.56], density: 0.92 },
};

export const CLOUD_TYPES = Object.keys(TYPES);
/** The type table, read-only to callers. Returns undefined for an unknown name rather than throwing. */
export function cloudType(name) { return TYPES[name]; }

/** One puff's size/colour/density, shared by both placements so a cumulus is a cumulus in either sky. */
function puffLook(t, r, i, n, sizeScale) {
    const rnd = (a, b) => a + r() * (b - a);
    const up = t.tower ? (i / n) : r() * 0.4;       // towering types stack upward; flat types spread sideways
    const w = rnd(t.w[0], t.w[1]) * (t.tower ? (1.0 - up * 0.35) : 1.0);
    const h = rnd(t.h[0], t.h[1]);
    return { up, w: w * sizeScale, h: h * sizeScale, colTop: t.colTop, colBot: t.colBot, density: t.density * rnd(0.8, 1.0) };
}

/**
 * THE FLAT PLACEMENT -- the engine's sky. Clusters scattered across a wrap box centred on (cx,cz) at the type's
 * own altitude. This is render/cloudLayer.js's original regenerate(), moved here verbatim in behaviour and given
 * a seed; the engine calls it with a fresh seed each time, so its sky is as varied as it was before.
 */
export function buildPuffsFlat({ type, cx = 0, cz = 0, region = 480, seed = 1 } = {}) {
    const t = TYPES[type];
    if (!t) return [];
    const r = rng(seed >>> 0);
    const rnd = (a, b) => a + r() * (b - a);
    const puffs = [];
    for (let c = 0; c < t.clouds; c++) {
        const baseX = cx + rnd(-region, region), baseZ = cz + rnd(-region, region), baseY = t.altitude;
        const n = Math.round(rnd(t.puffs[0], t.puffs[1]));
        for (let i = 0; i < n; i++) {
            const L = puffLook(t, r, i, n, 1);
            puffs.push({
                x: baseX + rnd(-t.spreadXZ, t.spreadXZ) * (t.tower ? 0.5 : 1.0),
                y: baseY + L.up * t.spreadY + rnd(-4, 4),
                z: baseZ + rnd(-t.spreadXZ, t.spreadXZ) * (t.tower ? 0.5 : 1.0),
                w: L.w, h: L.h, colTop: L.colTop, colBot: L.colBot, density: L.density,
            });
        }
    }
    return puffs;
}

/** Unit direction from spherical offsets around `dir`, using a geographic tangent frame (east/north). */
function offsetDir(dir, dEast, dNorth) {
    const d = norm(dir);
    let e = [d[2], 0, -d[0]];
    const l = Math.hypot(e[0], e[1], e[2]);
    e = l < 1e-6 ? [1, 0, 0] : [e[0] / l, e[1] / l, e[2] / l];
    const n = norm([d[1] * e[2] - d[2] * e[1], d[2] * e[0] - d[0] * e[2], d[0] * e[1] - d[1] * e[0]]);
    return norm([d[0] + e[0] * dEast + n[0] * dNorth, d[1] + e[1] * dEast + n[1] * dNorth, d[2] + e[2] * dEast + n[2] * dNorth]);
}
function norm(a) { const l = Math.hypot(a[0], a[1], a[2]) || 1; return [a[0] / l, a[1] / l, a[2] / l]; }

/**
 * *** THE SPHERICAL PLACEMENT -- weather on a WORLD, which is the half that did not exist. *** Clusters are
 * scattered inside a cone of half-angle `coverage` around `dir` (the part of the planet you are arriving at:
 * generating a whole globe's weather to fly through one patch of it is puffs nobody sees), and each sits on a
 * shell at `groundRadius + altitude`. "Up" for a puff is the planet's own radial direction there, so a towering
 * cumulonimbus grows away from the surface rather than along some world axis.
 *
 * ALTITUDE AND sizeScale COME FROM THE CALLER, deliberately -- see the header. A type's proportions are its
 * character and travel; its absolute altitude is a fact about the world it was written for and does not.
 */
export function buildPuffsShell({ type, center = [0, 0, 0], groundRadius = 17, altitude = 1.2,
                                  dir = [0, 0, 1], coverage = 0.45, sizeScale = 0.02, seed = 1 } = {}) {
    const t = TYPES[type];
    if (!t) return [];
    const r = rng(seed >>> 0);
    const rnd = (a, b) => a + r() * (b - a);
    const shell = groundRadius + altitude;
    const puffs = [];
    for (let c = 0; c < t.clouds; c++) {
        // a cluster centre inside the cone. sqrt keeps the scatter AREA-uniform rather than bunching at the
        // middle, which a naive uniform radius would do.
        const a = r() * Math.PI * 2, rad = Math.sqrt(r()) * coverage;
        const base = offsetDir(dir, Math.cos(a) * rad, Math.sin(a) * rad);
        const n = Math.round(rnd(t.puffs[0], t.puffs[1]));
        for (let i = 0; i < n; i++) {
            const L = puffLook(t, r, i, n, sizeScale);
            // spread within the cluster, expressed as an ANGLE so it is a real distance on the shell
            const sx = (rnd(-t.spreadXZ, t.spreadXZ) * (t.tower ? 0.5 : 1.0)) * sizeScale / shell;
            const sz = (rnd(-t.spreadXZ, t.spreadXZ) * (t.tower ? 0.5 : 1.0)) * sizeScale / shell;
            const d = offsetDir(base, sx, sz);
            const rr = shell + (L.up * t.spreadY + rnd(-4, 4)) * sizeScale;   // radial: the tower's own height
            puffs.push({
                x: center[0] + d[0] * rr, y: center[1] + d[1] * rr, z: center[2] + d[2] * rr,
                w: L.w, h: L.h, colTop: L.colTop, colBot: L.colBot, density: L.density,
                radius: rr,                        // handed out so a caller can test the shell without re-deriving it
                up: d,                             // the planet's radial direction here -- a puff's own "up"
            });
        }
    }
    return puffs;
}
