// WebGLEngine/physics/hmc/inference.js — v3282
// ---------------------------------------------------------------------------------------------------------------
// HMC graduates from device to INSTRUMENT: Bayesian parameter recovery, graded by two keys of different kinds.
//
// KEY ONE — EXACT (the hard key): Bayesian linear regression with known noise has a CLOSED-FORM Gaussian
// posterior (conjugacy): Sigma* = (X'X/s^2 + P0)^-1, mu* = Sigma* X'y/s^2. HMC must recover those moments to
// sampling error. No simulation is graded against itself; the reference is algebra.
//
// KEY TWO — CALIBRATION (the frequentist key): infer the frequency of a noisy oscillator signal, many times,
// each from fresh seeded data with a KNOWN true omega. The 90% credible interval must COVER the truth ~90% of
// the runs. Calibration is the check that a self-consistent-but-wrong sampler fails: an OVERCONFIDENT likelihood
// (noise understated) produces beautiful tight posteriors around plausible values — and its coverage collapses,
// which is measurable. sigmaWRONG is exported for exactly that measurement.
//
// INVERSE-CRIME HONESTY: the oscillator data is generated by the same signal model the likelihood assumes. That
// is deliberate and stated — the claim under test is THE SAMPLER AND THE INTERVALS, not the model, and the
// coverage key retains detection power over the failure that matters (wrong posterior width) precisely because
// the model is not in question. Model mis-specification is a different instrument.
// Gradients are ANALYTIC throughout (HMC's requirement); the RNG is seeded, so a failure reproduces.
// ---------------------------------------------------------------------------------------------------------------
"use strict";
import { makeRng, hmcStep } from "./hmc.js";

// ---- KEY ONE: exact conjugate posterior for linear regression ---------------------------------------------------
// model: y = a + b t + noise(sigma). Prior: independent N(0, tau^2) on (a, b). 2 params keeps the algebra exact
// and readable; the posterior is N(muStar, SigmaStar) in closed form.
function linearPosteriorExact(ts, ys, sigma, tau) {
    const n = ts.length, is2 = 1 / (sigma * sigma), ip2 = 1 / (tau * tau);
    let Stt = 0, St = 0, Sy = 0, Sty = 0;
    for (let i = 0; i < n; i++) { Stt += ts[i] * ts[i]; St += ts[i]; Sy += ys[i]; Sty += ts[i] * ys[i]; }
    // precision matrix A = X'X/s^2 + (1/tau^2) I  for X rows [1, t]
    const A00 = n * is2 + ip2, A01 = St * is2, A11 = Stt * is2 + ip2;
    const det = A00 * A11 - A01 * A01;
    const S00 = A11 / det, S01 = -A01 / det, S11 = A00 / det;   // SigmaStar
    const b0 = Sy * is2, b1 = Sty * is2;                        // X'y/s^2
    return { mu: [S00 * b0 + S01 * b1, S01 * b0 + S11 * b1], Sigma: [[S00, S01], [S01, S11]] };
}
// the target HMC samples for that model: U = -log posterior (up to a constant), analytic gradient.
function linearTarget(ts, ys, sigma, tau) {
    const is2 = 1 / (sigma * sigma), ip2 = 1 / (tau * tau);
    return {
        dim: 2, mu: [0, 0],
        U: (q) => { let s = 0; for (let i = 0; i < ts.length; i++) { const r = ys[i] - q[0] - q[1] * ts[i]; s += r * r; }
            return 0.5 * s * is2 + 0.5 * ip2 * (q[0] * q[0] + q[1] * q[1]); },
        gradU: (q) => { let g0 = ip2 * q[0], g1 = ip2 * q[1];
            for (let i = 0; i < ts.length; i++) { const r = ys[i] - q[0] - q[1] * ts[i]; g0 -= r * is2; g1 -= r * ts[i] * is2; }
            return [g0, g1]; },
    };
}

// ---- KEY TWO: oscillator frequency recovery + calibration -------------------------------------------------------
// model: y_i = A cos(omega t_i) + noise(sigma); infer (A, omega) with broad N(0, 100) priors. Analytic gradient.
function oscillatorData(Atrue, wTrue, sigma, n, rng) {
    const ts = [], ys = [];
    for (let i = 0; i < n; i++) { const t = i * 0.25; ts.push(t); ys.push(Atrue * Math.cos(wTrue * t) + sigma * rng.gauss()); }
    return { ts, ys };
}
function oscillatorTarget(ts, ys, sigmaLik) {
    const is2 = 1 / (sigmaLik * sigmaLik), ip2 = 1 / 10000;   // broad prior
    return {
        dim: 2, mu: [1, 1],
        U: (q) => { let s = 0; for (let i = 0; i < ts.length; i++) { const r = ys[i] - q[0] * Math.cos(q[1] * ts[i]); s += r * r; }
            return 0.5 * s * is2 + 0.5 * ip2 * (q[0] * q[0] + q[1] * q[1]); },
        gradU: (q) => { let gA = ip2 * q[0], gW = ip2 * q[1];
            for (let i = 0; i < ts.length; i++) { const c = Math.cos(q[1] * ts[i]), r = ys[i] - q[0] * c;
                gA -= r * c * is2; gW += r * q[0] * Math.sin(q[1] * ts[i]) * ts[i] * is2; }
            return [gA, gW]; },
    };
}

// run one posterior chain (thin wrapper over hmcStep with burn-in) and return kept samples.
function posteriorChain(target, q0, { n = 1500, burn = 300, eps = 0.02, L = 30, seed = 1 } = {}) {
    const rng = makeRng(seed);
    let q = q0.slice(); const kept = [];
    let accepted = 0;
    for (let i = 0; i < n + burn; i++) {
        const r = hmcStep(target, q, rng, { eps, L });
        q = r.q; if (r.accepted) accepted++;
        if (i >= burn) kept.push(q.slice());
    }
    return { samples: kept, acceptRate: accepted / (n + burn) };
}

function momentsOf(samples) {
    const n = samples.length, mean = [0, 0];
    for (const s of samples) { mean[0] += s[0]; mean[1] += s[1]; }
    mean[0] /= n; mean[1] /= n;
    const cov = [[0, 0], [0, 0]];
    for (const s of samples) { const a = s[0] - mean[0], b = s[1] - mean[1]; cov[0][0] += a * a; cov[0][1] += a * b; cov[1][1] += b * b; }
    cov[0][0] /= n - 1; cov[0][1] /= n - 1; cov[1][0] = cov[0][1]; cov[1][1] /= n - 1;
    return { mean, cov };
}
function centralInterval(vals, mass = 0.9) {
    const v = vals.slice().sort((a, b) => a - b), lo = (1 - mass) / 2;
    return [v[Math.floor(lo * v.length)], v[Math.min(v.length - 1, Math.floor((1 - lo) * v.length))]];
}

// CALIBRATION: `repeats` fresh datasets with the same known truth; count how often the 90% interval for omega
// covers it. sigmaLik defaults to the TRUE sigma; passing sigmaWRONG (understated) is the overconfidence
// sabotage the gate measures — beautiful tight posteriors whose coverage collapses.
function calibrationRun({ repeats = 40, Atrue = 2, wTrue = 1.3, sigma = 0.5, nData = 30,
                          sigmaLik = null, seed = 100, mass = 0.9 } = {}) {
    let covered = 0; const widths = [];
    const sl = sigmaLik == null ? sigma : sigmaLik;
    // THE STEP SCALES WITH THE LIKELIHOOD'S STEEPNESS (posterior sd ~ sigmaLik), or a steep sabotaged posterior
    // freezes the chain — and a frozen chain STARTED AT THE TRUTH fakes perfect coverage with zero-width
    // intervals, which is exactly what this harness did on its first run. Two defenses, both load-bearing:
    // eps proportional to sl, and the start OFFSET from the truth so freezing reads as coverage FAILURE.
    const eps = 0.015 * (sl / sigma);
    for (let r = 0; r < repeats; r++) {
        const rng = makeRng(seed + r * 7919);
        const { ts, ys } = oscillatorData(Atrue, wTrue, sigma, nData, rng);
        const target = oscillatorTarget(ts, ys, sl);
        const chain = posteriorChain(target, [Atrue + 0.35, wTrue + 0.1], { n: 1200, burn: 400, eps, L: 25, seed: seed + r });
        const iv = centralInterval(chain.samples.map((s) => s[1]), mass);
        widths.push(iv[1] - iv[0]);
        if (wTrue >= iv[0] && wTrue <= iv[1]) covered++;
    }
    return { covered, repeats, rate: covered / repeats, meanWidth: widths.reduce((a, b) => a + b, 0) / widths.length };
}

export { linearPosteriorExact, linearTarget, oscillatorData, oscillatorTarget, posteriorChain, momentsOf, centralInterval, calibrationRun };
if (typeof module !== "undefined" && module.exports) module.exports = { linearPosteriorExact, linearTarget, oscillatorData, oscillatorTarget, posteriorChain, momentsOf, centralInterval, calibrationRun };
