// FILE: world/orrerySeed.mjs -- v4189
//
// THE GIT LOG AS THE UNIVERSE'S SEED. A body's planet is generated by world/procPlanet.js, which needs a
// 32-bit integer; this turns the commit that brought the body into the tree into that integer.
//
// *** WHY THE SHA ALONE IS NOT THE SEED, WHICH IS A FACT ABOUT THIS REPOSITORY AND NOT A STYLE CHOICE. ***
// Nine of the fourteen vendored bodies share one first commit -- 66db97c45b52, the commit where vendor/ was
// first added. box3d, fonts, gifenc, htmx, jolt, krbn, slug, three and wasm all arrived in it. Seeding on the
// SHA alone would hand those nine THE SAME PLANET, and the picture would be quietly lying about how much
// variety the tree has. The name is folded in with it. This is the same underlying fact v4186 met from the
// other side, where those bodies came out co-orbital because they share an arrival DATE.
//
// *** AND THE WHOLE SHA IS USED, NOT ITS FIRST EIGHT CHARACTERS. *** parseInt(sha.slice(0, 8), 16) is the
// obvious one-liner and it throws away 128 of the 160 bits. It also happens to be the abbreviation git prints,
// so two commits that LOOK different in a log could seed identically. Folding every character costs nothing.
"use strict";

/**
 * FNV-1a over a string, to a uint32. Integer math only, so the same string gives the same number on every
 * machine -- the property the rest of this tree's determinism rests on (see world/orreryView.mjs's phaseFor
 * and world/procPlanet.js's mulberry32).
 */
export function fnv1a(str) {
    let h = 0x811c9dc5;
    const s = String(str == null ? "" : str);
    for (let i = 0; i < s.length; i++) {
        h ^= s.charCodeAt(i) & 0xff;
        h = Math.imul(h, 0x01000193) >>> 0;
    }
    return h >>> 0;
}

/** The separator matters: without it ("ab" + "c") and ("a" + "bc") would seed identically. */
export const SEP = " ";

/**
 * A body's planet seed.
 *
 * @param sha  the full commit hash that first added the body, or null when git cannot say
 * @param name the body's directory name
 */
export function seedFor(sha, name) {
    // *** A MISSING SHA IS NOT SEED 0. *** tools/ship/orreryScan.mjs is explicit that git failing to date a
    // path is a real answer (a shallow clone, a path never committed) rather than a default. Falling back to
    // 0 would give every undated body the same planet AND make it the same planet as a body whose SHA folded
    // to zero. The name alone still varies, and `seedProvenance` reports that the git half is missing.
    return fnv1a(String(sha || "") + SEP + String(name || "")) >>> 0;
}

/** Whether a seed actually came from the log, so a view can say so rather than implying it did. */
export function seedProvenance(sha) {
    return { sourced: !!(sha && /^[0-9a-f]{40}$/i.test(sha)), sha: sha || null };
}

/**
 * Seeds for a whole system, keyed by body name.
 * @param bodies [{ name, sha }]
 */
export function seedsFor(bodies = []) {
    const out = new Map();
    for (const b of (bodies || [])) if (b && b.name) out.set(b.name, seedFor(b.sha, b.name));
    return out;
}
