// FILE: world/world.js
// VERSION: v11 - COMMAND-INTEGRATED VOXEL CORE (MULTIPLAYER READY)

import { VOXEL } from "./voxelFormat.js";
import { biomeColumnMaterials, biomeHeightParams } from "./biomeTerrain.js";   // v2780 - Worley biome -> terrain materials + shape (feature-flagged)
import { Chunk } from "./chunk.js";
import { FluidSystem }      from "./fluidSystem.js";
import { RainSystem }       from "./rainSystem.js";
import { HydraulicErosion } from "./hydraulicErosion.js";
import { ErosionSystem }    from "./erosionSystem.js";
import { WaveSystem }       from "./waveSystem.js";
import { ErosionCache }     from "./erosion.js";   // round 135 — gen-time erosion
// v2797 — WASM terrain generation (Rust crate wasm-terrain/, optional; JS fallback below)
import { initTerrainWasm, wasmTerrainReady, wasmGenerateChunk, wasmHeightAt, wasmPrewarmTile, wasmTrimTiles, wasmStats } from "./terrainWasm.js";
// v2798 — terrain gen Web Worker (pre-bakes chunks off the main thread; same wasm binary → bit-identical)
import { initTerrainWorker, workerReady, workerCapacity, workerHasOrPending, workerRequestChunk, workerTakeChunk, workerTrimTiles, workerStats } from "./terrainWorkerClient.js";

export class VoxelWorld {

    constructor(noise = null) {

        this.noise = noise;

        this.chunkSize = 16;
        this.chunkHeight = 64;
        // v2780 - Worley biome terrain (feature-flagged, default OFF -> existing single-axis path).
        // Enable: window.__swekBiomes = true  OR  ?biomes=1  OR  localStorage voxelengine.biomes.worley=1
        this.useWorleyBiomes = (() => {
            try {
                if (typeof window !== "undefined" && window.__swekBiomes === true) return true;
                if (typeof location !== "undefined" && new URLSearchParams(location.search).get("biomes") === "1") return true;
                if (typeof localStorage !== "undefined" && localStorage.getItem("voxelengine.biomes.worley") === "1") return true;
            } catch {}
            return false;
        })();
        this.biomeSeed = 1337;
        // Round 41 — was 4 (144×144). Bumped to 7 (240×240) so player +
        // cinematic camera have more room before hitting unloaded void.
        this.gridRadius = 7;

        this.chunks = new Map();

        // --------------------------------------------------------
        // v2797 — WASM TERRAIN GENERATION (optional fast path)
        // --------------------------------------------------------
        // The Rust module (wasm-terrain/) reimplements _baseHeightAt +
        // erosion + generateChunk. It loads ASYNCHRONOUSLY, so the initial
        // grid below is always generated by the JS path; wasm takes over
        // for chunks in erosion tiles the JS path hasn't touched yet
        // (streamed chunks, growGrid rings, prewarmed tiles).
        //
        // TILE OWNERSHIP RULE: JS sin/cos and Rust sin/cos can differ by
        // 1 ulp, and hydraulic erosion amplifies that chaotically inside a
        // 128x128 tile. A tile must therefore be generated ENTIRELY by one
        // path. _wasmTiles records wasm-owned tiles; _heightAt routes
        // queries for those tiles into the wasm module so slopes, spawns,
        // and physics agree with the voxels on the ground.
        //
        // Disable: window.__swekWasmGen = false  OR  ?wasmgen=0
        //          OR  localStorage voxelengine.terrain.wasm = "0"
        this._wasmGenEnabled = (() => {
            try {
                if (typeof window !== "undefined" && window.__swekWasmGen === false) return false;
                if (typeof location !== "undefined" && new URLSearchParams(location.search).get("wasmgen") === "0") return false;
                if (typeof localStorage !== "undefined" && localStorage.getItem("voxelengine.terrain.wasm") === "0") return false;
            } catch {}
            return true;
        })();
        this._wasmTiles = new Set();   // "tx,tz" tiles owned by the wasm generator
        // v2798 — worker offload flag. The worker only spawns after the
        // main-thread wasm init succeeds (it imports the same pkg).
        // Disable: window.__swekWasmWorker = false  OR  ?wasmworker=0
        //          OR  localStorage voxelengine.terrain.worker = "0"
        this._wasmWorkerEnabled = (() => {
            try {
                if (typeof window !== "undefined" && window.__swekWasmWorker === false) return false;
                if (typeof location !== "undefined" && new URLSearchParams(location.search).get("wasmworker") === "0") return false;
                if (typeof localStorage !== "undefined" && localStorage.getItem("voxelengine.terrain.worker") === "0") return false;
            } catch {}
            return true;
        })();
        this._workerFeedKey = null;    // camera chunk key of the current feed queue
        this._workerFeedQueue = [];    // missing chunks (nearest first) to pre-bake
        this._wasmTrimCounter = 0;     // v2800 — frames until next tile-cache trim
        // v2801 — tiles whose JS erosion cache entry was TRIMMED but whose
        // ownership must stay JS (loaded chunks in them were JS-generated;
        // letting wasm claim them after the trim would mix generators
        // inside one tile — the exact seam the ownership rule prevents).
        this._jsTiles = new Set();
        if (this._wasmGenEnabled) {
            const cfg = {
                seed: this.biomeSeed,
                useWorley: this.useWorleyBiomes,
                chunkSize: this.chunkSize,
                chunkHeight: this.chunkHeight,
            };
            initTerrainWasm(cfg).then((ok) => {
                if (ok && this._wasmWorkerEnabled) initTerrainWorker(cfg);
            });
        }

        // --------------------------------------------------------
        // EXTERNAL CONTROL HOOK (CommandRouter / Excel / VBA)
        // --------------------------------------------------------
        this.commandBridge = null;

        // --------------------------------------------------------
        // SIMULATION SYSTEMS (rain -> fluid -> hydraulic erosion).
        // Constructed eagerly so other modules can hold references
        // (e.g. AI agents querying water density). All bounded with
        // hard caps; safe to leave running.
        // --------------------------------------------------------
        this.fluid     = new FluidSystem(this);
        this.rain      = new RainSystem(this);
        this.hydraulic = new HydraulicErosion(this);
        this.erosion   = new ErosionSystem(this);
        this.waves     = new WaveSystem();

        this.init();
    }

    // ------------------------------------------------------------
    // WORLD INIT
    // ------------------------------------------------------------
    init() {

        for (let cx = -this.gridRadius; cx <= this.gridRadius; cx++) {
            for (let cz = -this.gridRadius; cz <= this.gridRadius; cz++) {

                const chunk = this.generateChunk(cx, cz);
                this.chunks.set(`${cx},${cz}`, chunk);
            }
        }
        // Round 43f - perimeter stone walls so world bounds are visible
        this._paintBoundaryWalls();
    }

    // Round 48 - dynamic world growth. Set a new gridRadius and re-init
    // every chunk. Used by OgreScenario when a scenario asks for a
    // fieldLength larger than the current world can hold. No-op if the
    // requested radius equals the current value. Caller is responsible
    // for telling renderers/AI/whatever to invalidate any cached world
    // bounds; we fire `world:resized` via the commandBridge if present.
    setGridRadius(r) {
        r = Math.max(3, Math.min(16, r | 0));
        if (r === this.gridRadius) return this.gridRadius;
        const prev = this.gridRadius;
        this.gridRadius = r;
        this.chunks.clear();
        if (this._invalidateVisibleCache) this._invalidateVisibleCache();
        for (let cx = -this.gridRadius; cx <= this.gridRadius; cx++) {
            for (let cz = -this.gridRadius; cz <= this.gridRadius; cz++) {
                const chunk = this.generateChunk(cx, cz);
                chunk.dirty = true;
                this.chunks.set(`${cx},${cz}`, chunk);
            }
        }
        this._paintBoundaryWalls();
        console.log(`[World] gridRadius ${prev} -> ${r} (${this.chunks.size} chunks, ${r * this.chunkSize * 2}x${r * this.chunkSize * 2} voxels)`);
        if (this.commandBridge?.broadcast) {
            this.commandBridge.broadcast({ type: "world:resized", gridRadius: r, chunks: this.chunks.size });
        }
        return this.gridRadius;
    }

    // Round 291 — INCREMENTAL grow: keep existing chunks, generate only
    // the new outer ring. Cheaper than setGridRadius which wipes
    // everything and regenerates. Used by DynamicGridRadius to expand
    // view distance when FPS is comfortably high.
    //
    // Cost: one "ring" at radius R adds (2R+1)^2 - (2R-1)^2 = 8R new
    // chunks. At R=8 that's 64 new chunks ~ 50-100ms hitch. Caller
    // (DynamicGridRadius) only invokes this with hysteresis when FPS
    // is well above target, so the hitch comes out of headroom.
    growGrid(deltaR = 1) {
        const target = Math.max(3, Math.min(16, this.gridRadius + (deltaR | 0)));
        if (target === this.gridRadius) return this.gridRadius;
        if (target < this.gridRadius) return this.shrinkGrid(this.gridRadius - target);
        const prev = this.gridRadius;
        // Paint NEW ring(s) only — existing chunks stay
        for (let cx = -target; cx <= target; cx++) {
            for (let cz = -target; cz <= target; cz++) {
                // Skip the inner square that already exists
                if (Math.abs(cx) <= prev && Math.abs(cz) <= prev) continue;
                const key = `${cx},${cz}`;
                if (this.chunks.has(key)) continue;
                const chunk = this.generateChunk(cx, cz);
                chunk.dirty = true;
                this.chunks.set(key, chunk);
            }
        }
        this.gridRadius = target;
        if (this._invalidateVisibleCache) this._invalidateVisibleCache();
        // Boundary walls were stamped at the old perimeter — re-stamp
        // at the new one. The old walls inside the world will be
        // overwritten by chunk regen on the next dirty pass when the
        // boundary painter touches them; for now they remain as stone
        // strips inside the world (visible artifact, will erode away).
        this._paintBoundaryWalls();
        console.log(`[World] grew ${prev} -> ${target} (added ${this.chunks.size - (2 * prev + 1) ** 2} chunks, total ${this.chunks.size})`);
        if (this.commandBridge?.broadcast) {
            this.commandBridge.broadcast({ type: "world:resized", gridRadius: target, chunks: this.chunks.size });
        }
        return this.gridRadius;
    }

    // Round 291 — INCREMENTAL shrink: drop outer chunks. Cheap (no
    // generation). Called when FPS is below target and we've already
    // exhausted other knobs.
    shrinkGrid(deltaR = 1) {
        const target = Math.max(3, Math.min(16, this.gridRadius - (deltaR | 0)));
        if (target === this.gridRadius) return this.gridRadius;
        if (target > this.gridRadius) return this.growGrid(target - this.gridRadius);
        const prev = this.gridRadius;
        let dropped = 0;
        for (const key of Array.from(this.chunks.keys())) {
            const [cxs, czs] = key.split(",");
            const cx = +cxs, cz = +czs;
            if (Math.abs(cx) > target || Math.abs(cz) > target) {
                this.chunks.delete(key);
                dropped++;
            }
        }
        this.gridRadius = target;
        if (this._invalidateVisibleCache) this._invalidateVisibleCache();
        this._paintBoundaryWalls();
        console.log(`[World] shrunk ${prev} -> ${target} (dropped ${dropped} chunks, total ${this.chunks.size})`);
        if (this.commandBridge?.broadcast) {
            this.commandBridge.broadcast({ type: "world:resized", gridRadius: target, chunks: this.chunks.size });
        }
        return this.gridRadius;
    }

    // Round 43e — wipe every chunk and regenerate from the world gen.
    // Used by demo modes (OGRE, Lander, etc.) that need fresh terrain
    // each time they start, so they don't draw over the previous demo's
    // edits. Marks every chunk dirty so the renderer rebuilds meshes.
    regenerate() {
        this.chunks.clear();
        this._invalidateVisibleCache();   // round 43p
        for (let cx = -this.gridRadius; cx <= this.gridRadius; cx++) {
            for (let cz = -this.gridRadius; cz <= this.gridRadius; cz++) {
                const chunk = this.generateChunk(cx, cz);
                chunk.dirty = true;
                this.chunks.set(`${cx},${cz}`, chunk);
            }
        }
        // Round 43f — paint a stone wall around the world perimeter so
        // the boundary is visually obvious and players have a clear
        // "edge of the world" marker. 4 sides, height = chunkHeight/3.
        this._paintBoundaryWalls();
        console.log(`[World] regenerated ${this.chunks.size} chunks + boundary walls`);
        // Round 90 — notify subscribers (e.g. TreeSpawner) so they can
        // re-place their entities on the fresh terrain. Without this,
        // the tornado-wipe between OGRE cycles left a treeless world
        // because the trees lived as ECS entities that survived but no
        // longer had any matching surface beneath them.
        if (this._regenListeners) {
            for (const fn of this._regenListeners) {
                try { fn(); } catch (e) { console.warn("[World] regen listener threw:", e); }
            }
        }
    }

    // v456 — clean flat world for the BUILD VIEWER demo. Clears every chunk
    // to AIR and lays one thin floor plane, so a loaded schematic sits in an
    // empty room you can walk around instead of over procedural terrain.
    flatten({ floorY = 0, floorVoxel = VOXEL.STONE } = {}) {
        this.chunks.clear();
        this._invalidateVisibleCache();
        const S = this.chunkSize;
        for (let cx = -this.gridRadius; cx <= this.gridRadius; cx++) {
            for (let cz = -this.gridRadius; cz <= this.gridRadius; cz++) {
                const chunk = new Chunk(cx, cz, this.chunkSize, this.chunkHeight);   // all AIR
                if (floorY >= 0 && floorY < this.chunkHeight) {
                    for (let x = 0; x < S; x++)
                        for (let z = 0; z < S; z++)
                            chunk.set(x, floorY, z, floorVoxel);
                }
                chunk.dirty = true;
                this.chunks.set(`${cx},${cz}`, chunk);
            }
        }
        if (this._regenListeners) for (const fn of this._regenListeners) { try { fn(); } catch {} }
        console.log(`[World] flattened — clean floor at y=${floorY}`);
    }

    // Round 90 — subscribe to terrain regenerate events. Used by
    // TreeSpawner, decoration spawners, etc. to re-place their entities
    // when the world is wiped.
    onRegenerate(fn) {
        if (!this._regenListeners) this._regenListeners = new Set();
        this._regenListeners.add(fn);
        return () => this._regenListeners.delete(fn);   // unsubscribe
    }

    // Round 43g - boundary walls disabled by user request. OGRE
    // perimeter is now an invisible game-logic line only; default
    // terrain has no walls either. The method stays so OGRE could
    // re-enable visible walls if we ever want them back, but it's
    // never auto-called.
    _paintBoundaryWalls() {
        // Intentionally no-op in this round. Kept for API stability.
        return;
    }

    // Internal: forcibly write stone walls (used only if a caller
    // explicitly opts in; not invoked from init/regenerate any more).
    _paintBoundaryWallsForceVisible() {
        const extent = this.gridRadius * this.chunkSize;
        const wallHeight = Math.floor(this.chunkHeight / 3);
        const STONE = 1;
        for (let x = -extent; x < extent; x++) {
            for (let dy = 0; dy < wallHeight; dy++) {
                this.setVoxel(x, dy, -extent, STONE);
                this.setVoxel(x, dy,  extent - 1, STONE);
            }
        }
        for (let z = -extent; z < extent; z++) {
            for (let dy = 0; dy < wallHeight; dy++) {
                this.setVoxel(-extent,     dy, z, STONE);
                this.setVoxel( extent - 1, dy, z, STONE);
            }
        }
    }

    // ------------------------------------------------------------
    // CHUNK ACCESS
    // ------------------------------------------------------------
    getChunk(x, z) {

        const cx = Math.floor(x / this.chunkSize);
        const cz = Math.floor(z / this.chunkSize);

        return this.chunks.get(`${cx},${cz}`);
    }

    // ------------------------------------------------------------
    // VOXEL READ
    // ------------------------------------------------------------
    voxelAt(x, y, z) {

        const chunk = this.getChunk(x, z);
        if (!chunk) return VOXEL.AIR;

        const lx = x - chunk.cx * this.chunkSize;
        const lz = z - chunk.cz * this.chunkSize;

        return chunk.get(lx, y, lz);
    }

    getVoxel(x, y, z) {
        return this.voxelAt(x, y, z);
    }

    // Convenience used by sim systems (rain, fluid, erosion, hydraulic)
    // and by AI agents that probe space without setting voxels.
    isAir(x, y, z) {
        return this.voxelAt(x, y, z) === VOXEL.AIR;
    }

    // Round 38 — audio proximity helpers. Sample a sphere around the
    // camera position. Returns 0..1 where 1 = voxel of that material
    // is adjacent (≤1u away), 0 = none within radius.
    //
    // Uses a stride to keep per-frame cost low: ~5*5*5 = 125 voxelAt
    // calls for water/lava (radius 12, stride 3). voxelAt is a hash
    // lookup on chunks Map, so this is cheap.
    getWaterProximity(pos, radius = 12) {
        return this._proximityScan(pos, radius, VOXEL.WATER);
    }

    getLavaProximity(pos, radius = 14) {
        return this._proximityScan(pos, radius, VOXEL.LAVA);
    }

    _proximityScan(pos, radius, voxelId) {
        if (!pos) return 0;
        const stride = 3;
        let closestSq = Infinity;
        const cx = Math.floor(pos.x), cy = Math.floor(pos.y), cz = Math.floor(pos.z);
        for (let dx = -radius; dx <= radius; dx += stride) {
            for (let dy = -radius; dy <= radius; dy += stride) {
                for (let dz = -radius; dz <= radius; dz += stride) {
                    const v = this.voxelAt(cx + dx, cy + dy, cz + dz);
                    if (v === voxelId) {
                        const d2 = dx * dx + dy * dy + dz * dz;
                        if (d2 < closestSq) closestSq = d2;
                    }
                }
            }
        }
        if (closestSq === Infinity) return 0;
        const dist = Math.sqrt(closestSq);
        return Math.max(0, 1 - dist / radius);
    }

    // Round 38 — caveFactor. Counts non-air voxels in a 9x9x9 sample
    // sphere around camera. 0 = open sky, 1 = fully enclosed. Drives
    // reverb mix toward "cave" when high.
    getCaveFactor(pos) {
        if (!pos) return 0;
        const cx = Math.floor(pos.x), cy = Math.floor(pos.y), cz = Math.floor(pos.z);
        let solid = 0, total = 0;
        for (let dx = -4; dx <= 4; dx += 2) {
            for (let dy = -3; dy <= 5; dy += 2) {
                for (let dz = -4; dz <= 4; dz += 2) {
                    if (this.voxelAt(cx + dx, cy + dy, cz + dz) !== VOXEL.AIR) solid++;
                    total++;
                }
            }
        }
        // Normalize: at 70% solid we call it "fully cave". Linear ramp.
        return Math.min(1.0, solid / (total * 0.7));
    }

    // Round 38 — true if camera is inside a water voxel. Triggers the
    // muffling lowpass filter on master.
    isUnderwater(pos) {
        if (!pos) return false;
        const cx = Math.floor(pos.x), cy = Math.floor(pos.y), cz = Math.floor(pos.z);
        return this.voxelAt(cx, cy, cz) === VOXEL.WATER;
    }

    // Compatibility shim: my AI/civ code calls ensureChunksLoaded() to
    // expand the loaded radius. This world uses a fixed grid (init()
    // pre-loads all chunks within gridRadius), so this is a no-op.
    ensureChunksLoaded(/* keys */) {
        // no-op for fixed-grid world
    }

    // ------------------------------------------------------------
    // VOXEL WRITE (COMMAND-AWARE)
    // ------------------------------------------------------------
    setVoxel(x, y, z, v) {

        const chunk = this.getChunk(x, z);
        if (!chunk) return;

        const lx = x - chunk.cx * this.chunkSize;
        const lz = z - chunk.cz * this.chunkSize;

        chunk.set(lx, y, lz, v);
        chunk.dirty = true;
        // Persistence flag — never auto-cleared. Set on every setVoxel
        // (sim, command router, debug API) so any chunk diverging from
        // the noise-generated terrain gets saved by WorldPersistence.
        chunk._modified = true;

        // --------------------------------------------------------
        // EXTERNAL SYNC (Excel / VBA / Network / Debug UI)
        // --------------------------------------------------------
        if (this.commandBridge) {
            this.commandBridge.emit("voxel:set", { x, y, z, v });
        }
    }

    // ------------------------------------------------------------
    // VISIBILITY
    // ------------------------------------------------------------
    // Round 43p - cached array. world.chunks is a Map; Array.from()
    // every frame allocates ~225 entries × ~60fps = 13.5k unnecessary
    // allocations/sec. Now we cache the array and invalidate when the
    // map membership changes (chunk add / remove).
    getVisibleChunks() {
        if (this._visibleArr && this._visibleArrSize === this.chunks.size) {
            return this._visibleArr;
        }
        this._visibleArr = Array.from(this.chunks.values());
        this._visibleArrSize = this.chunks.size;
        return this._visibleArr;
    }

    _invalidateVisibleCache() {
        this._visibleArr = null;
        this._visibleArrSize = -1;
    }

    // ------------------------------------------------------------
    // CHUNK GENERATION (multi-frequency rolling terrain + biome system).
    // _biomeAt returns a low-frequency continuous noise that smoothly
    // varies the base height + amplitude across the world; _heightAt
    // mixes that with the existing detail layers so biome transitions
    // are smooth (no cliffs at boundaries). generateChunk uses the
    // discrete biome bucket for surface/mid-layer material choice —
    // sharp color edges between biomes look intentional, like the
    // grass-to-sand transition where a forest meets a beach.
    //
    // Three biomes: DESERT (low, flat, sand all the way), PLAINS
    // (current behavior — gentle hills, slope-aware grass/dirt/sand),
    // and MOUNTAIN (high, dramatic, stone-exposed peaks).
    //
    // After terrain pass, AIR cells below WATER_LEVEL become WATER —
    // gives naturally low areas a coastline + shallow shelf.
    // ------------------------------------------------------------

    _biomeAt(wx, wz) {
        // Very low frequency so each biome spans ~80-150 voxels
        // (about 5-10 chunks) — large enough to read as distinct
        // regions, small enough to fit several biomes in view.
        return (
            Math.sin(wx * 0.012) * Math.cos(wz * 0.011) +
            0.4 * Math.sin((wx + wz) * 0.018)
        );
    }

    // Round 135 — public heightAt routes through the erosion cache.
    // First call to any column in a new 128x128 tile triggers a
    // one-time erosion pass for that tile (~30-80ms). All subsequent
    // queries against any cell in the same tile are O(1) array reads.
    // The cache is created lazily on first call so existing test
    // harnesses that construct a VoxelWorld without ever calling
    // _heightAt pay zero overhead.
    _heightAt(wx, wz) {
        // v1096 — Real Terrain override (Stage 2). When a real-world heightmap is
        // loaded, it answers for its region; null elsewhere -> procedural below.
        if (this._heightOverride) {
            const ov = this._heightOverride(wx, wz);
            if (ov !== null && ov !== undefined) return Math.max(1, Math.min(this.chunkHeight - 1, Math.floor(ov)));
        }
        // v2797 — wasm-owned tiles answer from the wasm erosion cache so
        // every consumer (slope, spawns, physics) matches the wasm voxels.
        if (this._wasmTiles.size > 0) {
            const tk = Math.floor(wx / 128) + "," + Math.floor(wz / 128);
            if (this._wasmTiles.has(tk)) {
                const wh = wasmHeightAt(wx, wz);
                if (wh !== null) return wh;
                // wasm demoted itself mid-session — fall through to JS.
            }
        }
        if (!this._erosionCache) {
            this._erosionCache = new ErosionCache(
                (x, z) => this._baseHeightAt(x, z)
            );
            // Expose for console debugging: window._erosion.dumpStats()
            if (typeof window !== "undefined") {
                window._erosion = this._erosionCache;
            }
        }
        const h = this._erosionCache.heightAt(wx, wz);
        // Clamp to chunk bounds (same as _baseHeightAt did before).
        return Math.max(1, Math.min(this.chunkHeight - 1, Math.floor(h)));
    }

    // Round 133 — domain warping + ridged multifractal for natural
    // terrain shapes. Round 135 — this is now the BASE function
    // (un-eroded). The public _heightAt above queries an erosion cache
    // that runs hydraulic + thermal erosion on top of this output,
    // carving real river valleys and weathering peaks.
    _baseHeightAt(wx, wz) {
        // v2780b - Worley biome drives base elevation, amplitude AND noise profile when enabled; otherwise the
        // original single-axis scalar. base/amp are set here so the rest of the function is unchanged.
        let kind, base, amp;
        if (this.useWorleyBiomes) {
            const hp = biomeHeightParams(wx, wz, this.biomeSeed);
            kind = hp.kind; base = hp.base; amp = hp.ampMul;
        } else {
            const biome = this._biomeAt(wx, wz);
            kind = this._biomeKind(biome);
            base = 20 + biome * 4;
            amp = Math.max(0.4, Math.min(1.5, 1.0 + biome * 0.5));
        }

        // Round 133 — DOMAIN WARPING. Displace the sample coordinates
        // by a low-frequency noise field before sampling the height
        // noise. This breaks up the regular sin·cos grid pattern that
        // was visible in earlier rounds: peaks no longer line up on
        // perpendicular axes, and rolling hills feel organic instead
        // of woven. The warp scale (8u) is chosen so visible terrain
        // features displace by a noticeable fraction of their own
        // wavelength without scrambling them entirely.
        const warpX = Math.sin(wx * 0.018 + 0.7) * Math.cos(wz * 0.022) * 8;
        const warpZ = Math.cos(wx * 0.021)       * Math.sin(wz * 0.019 + 1.2) * 8;
        const sx = wx + warpX;
        const sz = wz + warpZ;

        // base + amp were computed above (biome-driven, flag-aware)

        let hill;
        if (kind === "mountain") {
            // Round 133 — RIDGED MULTIFRACTAL for mountains. Standard
            // fBm (sum of noise octaves) gives rounded hills; ridged
            // noise uses 1 - |noise| per octave, which folds the noise
            // around its zero-crossings into sharp ridges. Squaring the
            // first ridge octave sharpens it further; multiplying the
            // higher-frequency octaves by the base ridge masks them to
            // only show on the ridge crests (so valleys stay smooth
            // while peaks are craggy).
            const r1 = 1 - Math.abs(Math.sin(sx * 0.04) * Math.cos(sz * 0.04));
            const r2 = 1 - Math.abs(Math.sin(sx * 0.09 + 1.7));
            const r3 = 1 - Math.abs(Math.cos(sz * 0.11 + 0.3));
            const ridge = (r1 * r1 * 14)         // primary sharp ridge
                        + (r2 * r1 *  4)         // ridge-masked secondary
                        + (r3 * r1 *  3)         // ridge-masked tertiary
                        + (Math.sin(sx * 0.27) * Math.cos(sz * 0.27) * 2);
            // Round 133 — VALLEY CARVING. Where r1 is small (between
            // ridges), dig the terrain down a few extra voxels. This
            // creates pronounced river-valley basins between mountain
            // crests without needing full hydraulic erosion simulation
            // (that's step 4 on the roadmap). Cheap, single subtract.
            const valleyDip = Math.max(0, 0.35 - r1) * 12;
            hill = ridge - valleyDip + Math.sin((wx + wz) * 0.4);
        } else {
            // Plains/desert — original 5-octave fBm. Domain-warped
            // input coords give the rolling hills a more organic feel
            // without the periodic "weave" pattern. Last octave uses
            // un-warped coords so the highest-frequency surface jitter
            // stays crisp instead of being smeared by the warp.
            hill =
                12 * Math.sin(sx * 0.04) * Math.cos(sz * 0.04) +
                 5 * Math.sin(sx * 0.09 + 1.7) +
                 3 * Math.cos(sz * 0.11 + 0.3) +
                 3 * Math.sin(sx * 0.27) * Math.cos(sz * 0.27) +
                 1 * Math.sin((wx + wz) * 0.4);
        }

        // Clamp into [1, chunkHeight-1] so peaks don't punch through
        // the chunk top and valleys leave at least one bedrock layer.
        const h = Math.floor(base + hill * amp);
        return Math.max(1, Math.min(this.chunkHeight - 1, h));
    }

    _biomeKind(biome) {
        if (biome < -0.5) return "desert";
        if (biome >  0.5) return "mountain";
        return "plains";
    }

    // Cave density — two-channel 3D noise. Where BOTH channels happen
    // to be near zero, we get the intersection of two iso-surfaces in
    // 3D, which is a 1D curve = tunnel-shaped cavities. Threshold the
    // sum of |a|+|b| against CAVE_THRESHOLD to widen the tunnels into
    // walkable air pockets. Returns roughly [0, 3]; lower = more
    // tunnel-like.
    _caveDensityAt(wx, wy, wz) {
        const a = Math.sin(wx * 0.06) *
                  Math.cos(wy * 0.05) *
                  Math.sin(wz * 0.06);
        const b = Math.sin(wx * 0.04 + 1.7) *
                  Math.cos(wz * 0.05 + 0.3) +
                  Math.sin(wy * 0.07);
        return Math.abs(a) + Math.abs(b);
    }

    // v2798 — tile-ownership rule, factored out so the worker feed can
    // pre-check it. Returns the "tx,tz" tiles a chunk touches (including
    // the ±1-voxel slope apron), or null if the chunk may not go wasm.
    _wasmSpannedTiles(cx, cz) {
        if (!this._wasmGenEnabled) return null;
        if (this._heightOverride) return null;         // real-terrain stamps stay JS
        const S = this.chunkSize, T = 128;
        const spanned = new Set();
        for (const wx of [cx * S - 1, cx * S + S]) {
            for (const wz of [cz * S - 1, cz * S + S]) {
                spanned.add(Math.floor(wx / T) + "," + Math.floor(wz / T));
            }
        }
        for (const k of spanned) {
            if (this._wasmTiles.has(k)) continue;
            if (this._jsTiles.has(k)) return null;                                  // JS owned (tile trimmed)
            if (this._erosionCache && this._erosionCache.tiles.has(k)) return null; // JS owns it
        }
        return spanned;
    }

    // v2797/v2798 — wasm chunk attempt. Order: worker-baked chunk (free),
    // then synchronous main-thread wasm. Worker output is bit-identical to
    // sync wasm (same binary), so both claim tiles under the same rule.
    _tryWasmChunk(cx, cz) {
        const spanned = this._wasmSpannedTiles(cx, cz);
        if (!spanned) return null;
        let vox = workerTakeChunk(`${cx},${cz}`);
        if (!vox) {
            if (!wasmTerrainReady()) return null;
            vox = wasmGenerateChunk(cx, cz);
        }
        if (!vox) return null;
        for (const k of spanned) this._wasmTiles.add(k);
        return vox;
    }

    // v2797/v2798 — frame-budget terrain prewarm, path-aware. main.js calls
    // this instead of world._erosionCache.prewarm directly. When wasm is
    // active: (a) warm ONE nearest unowned erosion tile in the main-thread
    // instance (keeps _heightAt stall-free), and (b) feed the gen worker
    // up to its capacity with the nearest missing chunks so streamed loads
    // become free cache hits. Otherwise defer to the JS prewarmer.
    prewarmTerrain(camX, camZ, budgetMs = 3) {
        if (this._wasmGenEnabled && wasmTerrainReady()) {
            const ctx = Math.floor(camX / 128);
            const ctz = Math.floor(camZ / 128);
            const R = 2;
            let best = null, bestD = Infinity;
            for (let dz = -R; dz <= R; dz++) {
                for (let dx = -R; dx <= R; dx++) {
                    const tx = ctx + dx, tz = ctz + dz;
                    const k = tx + "," + tz;
                    if (this._wasmTiles.has(k)) continue;
                    if (this._jsTiles.has(k)) continue;                                  // JS owned (trimmed)
                    if (this._erosionCache && this._erosionCache.tiles.has(k)) continue; // JS-owned
                    const d = dx * dx + dz * dz;
                    if (d < bestD) { bestD = d; best = { tx, tz, k }; }
                }
            }
            if (best && wasmPrewarmTile(best.tx, best.tz)) {
                this._wasmTiles.add(best.k);
            }
            this._feedWorker(camX, camZ);
            // v2800 — every ~300 calls (≈5s at 60fps), trim erosion tiles
            // beyond Chebyshev radius 5 of the camera tile in BOTH wasm
            // instances. Safe: trimmed tiles regenerate identically on
            // demand; _wasmTiles ownership is kept so a re-entered tile
            // still routes to the wasm path. Bounds long-session memory
            // (~65KB per tile per instance).
            if (++this._wasmTrimCounter >= 300) {
                this._wasmTrimCounter = 0;
                wasmTrimTiles(ctx, ctz, 5);
                workerTrimTiles(ctx, ctz, 5);
            }
            return;
        }
        if (this._erosionCache) {
            this._erosionCache.prewarm(camX, camZ, budgetMs);
            // v2801 — mirror of the wasm tile trim for the JS cache. Every
            // ~300 calls, drop tiles beyond Chebyshev radius 5 of the
            // camera tile; record them in _jsTiles so ownership stays JS.
            if (++this._wasmTrimCounter >= 300) {
                this._wasmTrimCounter = 0;
                const trimmed = this._erosionCache.trimTiles(
                    Math.floor(camX / 128), Math.floor(camZ / 128), 5);
                for (const k of trimmed) this._jsTiles.add(k);
            }
        }
    }

    // v2798 — keep the gen worker busy pre-baking the nearest missing
    // chunks around the camera. The queue rebuilds when the camera enters
    // a new chunk (mirrors ChunkStreamer's radiate-outward order) and
    // drains at the worker's capacity, so cost per frame is O(radius²)
    // only on chunk changes and O(capacity) otherwise.
    _feedWorker(camX, camZ) {
        if (!workerReady()) return;
        const cs = this.chunkSize;
        const ccx = Math.floor(camX / cs);
        const ccz = Math.floor(camZ / cs);
        const camKey = ccx + "," + ccz;
        if (camKey !== this._workerFeedKey) {
            this._workerFeedKey = camKey;
            const r = Math.min(this.gridRadius, 8);
            const cand = [];
            for (let dx = -r; dx <= r; dx++) {
                for (let dz = -r; dz <= r; dz++) {
                    const tcx = ccx + dx, tcz = ccz + dz;
                    if (this.chunks.has(`${tcx},${tcz}`)) continue;
                    cand.push({ cx: tcx, cz: tcz, d2: dx * dx + dz * dz });
                }
            }
            cand.sort((a, b) => a.d2 - b.d2);
            this._workerFeedQueue = cand;
        }
        let cap = workerCapacity();
        while (cap > 0 && this._workerFeedQueue.length > 0) {
            const c = this._workerFeedQueue.shift();
            const k = `${c.cx},${c.cz}`;
            if (this.chunks.has(k) || workerHasOrPending(k)) continue;
            if (!this._wasmSpannedTiles(c.cx, c.cz)) continue;   // JS-owned area
            if (workerRequestChunk(c.cx, c.cz)) cap--;
        }
    }

    // Console debugging: window.world.wasmGenStats()
    wasmGenStats() {
        return { ...wasmStats(), tilesOwned: this._wasmTiles.size, worker: workerStats() };
    }

    generateChunk(cx, cz) {

        const chunk = new Chunk(cx, cz, this.chunkSize, this.chunkHeight);

        // v2797 — wasm fast path: whole-chunk fill in one boundary crossing.
        const wasmVox = this._tryWasmChunk(cx, cz);
        if (wasmVox) {
            chunk.voxels = wasmVox;   // same length/layout; replaces the blank array
            return chunk;             // dirty=true from the constructor
        }

        const S = this.chunkSize;
        const H = this.chunkHeight;
        const WATER_LEVEL         = 8;     // AIR cells below this become ocean
        const CAVE_THRESHOLD      = 0.3;   // lower = sparser caves; ~7% of stone at 0.3
        const CAVE_CEILING_BUFFER = 4;     // keep caves this far below the surface

        for (let x = 0; x < S; x++) {
            for (let z = 0; z < S; z++) {

                const wx = cx * S + x;
                const wz = cz * S + z;

                const height = this._heightAt(wx, wz);
                const biome  = this._biomeAt(wx, wz);
                const kind   = this._biomeKind(biome);

                // Slope = max abs height delta to any 4-neighbour.
                const dN = Math.abs(this._heightAt(wx,   wz - 1) - height);
                const dS = Math.abs(this._heightAt(wx,   wz + 1) - height);
                const dE = Math.abs(this._heightAt(wx + 1, wz)   - height);
                const dW = Math.abs(this._heightAt(wx - 1, wz)   - height);
                const slope = Math.max(dN, dS, dE, dW);

                // Per-biome surface + mid-layer choice. Mountains expose
                // stone at their peaks; deserts are sand all the way
                // down; plains keep the slope-aware grass/dirt/sand mix
                // from the previous terrain function.
                let surfaceType;
                let midLayer = VOXEL.DIRT;
                if (this.useWorleyBiomes) {
                    // v2780 - 2-axis Worley biome drives surface + subsurface materials (with elevation overrides)
                    const bm = biomeColumnMaterials(wx, wz, this.biomeSeed, height, { slope, waterLevel: WATER_LEVEL });
                    surfaceType = bm.surface;
                    midLayer    = bm.sub;
                } else if (kind === "desert") {
                    surfaceType = VOXEL.SAND;
                    midLayer    = VOXEL.SAND;
                } else if (kind === "mountain") {
                    midLayer = VOXEL.STONE;          // less dirt under peak
                    if (height > 36)      surfaceType = VOXEL.STONE;  // bare rock
                    else if (slope >= 2)  surfaceType = VOXEL.DIRT;
                    else                  surfaceType = VOXEL.GRASS;
                } else {
                    // plains — original logic
                    if (height <= 10)     surfaceType = VOXEL.SAND;
                    else if (slope >= 2)  surfaceType = VOXEL.DIRT;
                    else                  surfaceType = VOXEL.GRASS;
                }

                for (let y = 0; y < H; y++) {

                    let v = VOXEL.AIR;

                    if (y < height - 4)         v = VOXEL.STONE;
                    else if (y < height - 1)    v = midLayer;
                    else if (y === height - 1)  v = surfaceType;

                    if (v !== VOXEL.AIR) {
                        chunk.set(x, y, z, v);
                    }
                }

                // Cave carve pass. Only target STONE cells, only below
                // surface - CAVE_CEILING_BUFFER (so the visible top
                // never has random holes), only above bedrock (y >= 1).
                // Underwater caves auto-flood: carved cells below
                // WATER_LEVEL become WATER instead of AIR so we don't
                // get dry pockets surrounded by ocean.
                const caveTop = height - CAVE_CEILING_BUFFER;
                for (let y = 1; y < caveTop; y++) {
                    if (chunk.get(x, y, z) !== VOXEL.STONE) continue;
                    if (this._caveDensityAt(wx, y, wz) < CAVE_THRESHOLD) {
                        chunk.set(x, y, z, y < WATER_LEVEL ? VOXEL.WATER : VOXEL.AIR);
                    }
                }

                // Ocean fill — AIR cells below WATER_LEVEL become WATER.
                // Cells above terrain at this (x,z) are AIR; below the
                // surface they're already STONE/DIRT/SAND so the
                // idempotent chunk.set short-circuits. Net effect: low
                // terrain gets a flooded shelf up to WATER_LEVEL.
                for (let y = 0; y < WATER_LEVEL; y++) {
                    if (chunk.get(x, y, z) === VOXEL.AIR) {
                        chunk.set(x, y, z, VOXEL.WATER);
                    }
                }
            }
        }

        return chunk;
    }

    // ------------------------------------------------------------
    // SIMULATION TICK
    // Called from main.js loop (typically throttled to 10Hz). Runs
    // rain -> fluid -> hydraulic + waves. All systems are bounded
    // by their own caps so this is cheap regardless of cadence.
    // ------------------------------------------------------------
    simulate(dt = 0.1) {
        this.rain.update();
        this.rain.step();
        this.fluid.update();
        this.hydraulic.update();
        this.erosion.update();
        this.waves.update(dt);
    }

    // v329 — diagnostic. Print which chunks are loaded relative to a
    // reference position (default: world origin, but pass camera.position
    // for a camera-centered view). Helps diagnose "one side of terrain
    // missing" symptoms by showing chunk presence asymmetrically.
    //
    // Output: an ASCII map where '#' = loaded chunk, '.' = missing.
    // The center '@' marks the reference chunk. Range is gridRadius.
    //
    // v333 — was firing 18+ separate console.log calls (header + 15 rows
    // + 2 separators), which caused a visible frame stagger in Chrome
    // because the dev-console flush is synchronous. Now builds the full
    // output string and emits a single console.log. No stagger.
    dumpChunkGrid(refX = 0, refZ = 0) {
        const r = this.gridRadius;
        const cs = this.chunkSize;
        const refCX = Math.floor(refX / cs);
        const refCZ = Math.floor(refZ / cs);
        const lines = [];
        let loaded = 0, missing = 0;
        // Top of map = -Z (north), bottom = +Z (south)
        for (let dz = -r; dz <= r; dz++) {
            let line = "";
            for (let dx = -r; dx <= r; dx++) {
                const cx = refCX + dx;
                const cz = refCZ + dz;
                const here = (dx === 0 && dz === 0);
                if (this.chunks.has(`${cx},${cz}`)) {
                    line += here ? "@" : "#";
                    loaded++;
                } else {
                    line += here ? "?" : ".";
                    missing++;
                }
            }
            lines.push(line);
        }
        const total = loaded + missing;
        const header = `[chunkGrid] ref=(${refX|0},${refZ|0}) chunk=(${refCX},${refCZ}) ` +
                       `gridRadius=${r} loaded=${loaded}/${total} ` +
                       `(${(100*loaded/total).toFixed(0)}%)`;
        const body = "  N\n" + lines.map(l => "  " + l).join("\n") + "\n  S";
        console.log(header + "\n" + body);
        return { loaded, missing, total, refCX, refCZ };
    }

    // v336 — one-shot cleanup. Walk every loaded chunk and clear
    // STONE / SNOW voxels above `maxY`. Use to flatten over-tall
    // mountains in a world that was painted multiple times before
    // the v336 idempotency fix landed. Natural single-pass mountains
    // cap around Y=30; setting maxY=30 is a safe default that
    // preserves intentional peaks while truncating stacked cliffs.
    //
    // Returns { columnsTouched, voxelsCleared, maxY }.
    knockDownMountains(maxY = 30) {
        let columnsTouched = 0;
        let voxelsCleared = 0;
        for (const [, chunk] of this.chunks) {
            const cx = chunk.cx, cz = chunk.cz;
            for (let lx = 0; lx < this.chunkSize; lx++) {
                for (let lz = 0; lz < this.chunkSize; lz++) {
                    const wx = cx * this.chunkSize + lx;
                    const wz = cz * this.chunkSize + lz;
                    let columnTouched = false;
                    // Scan from world ceiling down to maxY+1. Anything
                    // STONE (id 1) or SNOW (id 5) gets cleared.
                    const SCAN_TOP = 120;
                    for (let y = SCAN_TOP; y > maxY; y--) {
                        const v = this.voxelAt(wx, y, wz);
                        if (v === 1 || v === 5) {
                            this.setVoxel(wx, y, wz, 0);
                            voxelsCleared++;
                            columnTouched = true;
                        }
                    }
                    if (columnTouched) columnsTouched++;
                }
            }
        }
        console.log(`[world] knockDownMountains(maxY=${maxY}): cleared ${voxelsCleared} voxels across ${columnsTouched} columns`);
        return { columnsTouched, voxelsCleared, maxY };
    }
}