// ai-bridge/brewFormulaBridge.js — v1818
// Generates a REAL, working Homebrew formula + tap instructions so the SweK Engine
// can be installed on a Mac with `brew install swek-engine`.
//
// HONEST SCOPE — what this does and does NOT do:
//  - DOES: compute the sha256 of a published release zip, and emit a correct Ruby
//    Formula that downloads that zip, installs it into Homebrew's libexec, runs
//    `npm install` for the bridge deps, and drops a `swek-engine` launcher on the PATH.
//  - DOES: give you the exact `brew tap` / `brew install` commands.
//  - DOES NOT: create the public `homebrew-swek` tap repo for you, or push the
//    formula to it. Homebrew installs from a PUBLIC formula; that repo has to exist
//    and host the .rb file. The engine can publish the release (createRelease/
//    uploadAsset) and generate the formula text — committing it to the tap repo is a
//    one-time GitHub step (which the engine CAN do via the GitHub API if you give it
//    a token + let it create the repo, but that's a deliberate, separate action).
//
// So: `brew install` from a Mac WILL install the engine — once the formula below is
// committed to a public tap. This module produces that formula honestly (real sha256,
// real URL), instead of pretending a button installs it.
"use strict";
const fs = require("fs");
const crypto = require("crypto");
const path = require("path");

// sha256 of a local file (the release zip), streamed so large files don't blow memory.
function sha256File(filePath) {
    return new Promise((resolve, reject) => {
        try {
            const h = crypto.createHash("sha256");
            const s = fs.createReadStream(filePath);
            s.on("data", (d) => h.update(d));
            s.on("end", () => resolve(h.digest("hex")));
            s.on("error", reject);
        } catch (e) { reject(e); }
    });
}

// builds the Ruby Formula text. The engine zip extracts to EngineProject_vNNNN/WebGLEngine/...
// so the formula installs that subtree into libexec and writes a launcher that runs the
// Node bridge from there.
function formulaText({ version, url, sha256, owner }) {
    const v = String(version || "0").replace(/^v/, "");
    owner = owner || "HowdyKeith";
    // Homebrew formula class name is derived from the formula file name (swek-engine -> SwekEngine)
    return `# typed: false
# frozen_string_literal: true

# Homebrew formula for the SweK Engine — a multi-runtime WebGL2 / Node.js LAN
# portfolio engine. Generated by the engine itself (brewFormulaBridge.js).
#
# Install:
#   brew tap ${owner.toLowerCase()}/swek
#   brew install swek-engine
#
# Run after install:
#   swek-engine            # starts the bridge on :8787 and opens server.html
class SwekEngine < Formula
  desc "Multi-runtime WebGL2 / Node.js LAN portfolio engine (SweK)"
  homepage "https://github.com/${owner}/SweK-Engine"
  url "${url}"
  sha256 "${sha256}"
  version "${v}"
  license "MIT"

  depends_on "node"

  def install
    # the release zip contains EngineProject_vNNNN/WebGLEngine/... — install the
    # WebGLEngine subtree (the actual app) into libexec.
    engine_root = Dir["EngineProject_*/WebGLEngine"].first || Dir["**/WebGLEngine"].first
    odie "WebGLEngine folder not found in the release archive" if engine_root.nil?

    libexec.install Dir["#{engine_root}/*"]

    # install the bridge's pure-JS dependencies
    system "npm", "install", "--prefix", "#{libexec}/ai-bridge", *Language::Node.local_npm_install_args if File.exist?("#{libexec}/ai-bridge/package.json")

    # a small launcher on the PATH: starts the bridge and opens the console.
    (bin/"swek-engine").write <<~SH
      #!/bin/bash
      cd "#{libexec}" || exit 1
      PORT="\${SWEK_PORT:-8787}"
      echo "SweK Engine v${v} — starting bridge on :$PORT"
      # open the console once the port answers (best-effort, non-blocking)
      ( for i in $(seq 1 30); do
          if curl -s "http://localhost:$PORT/server.html" >/dev/null 2>&1; then
            open "http://localhost:$PORT/server.html" 2>/dev/null; break
          fi
          sleep 1
        done ) &
      exec node ai-bridge/server.js
    SH
    chmod 0755, bin/"swek-engine"
  end

  def caveats
    <<~EOS
      SweK Engine installed. Start it with:
        swek-engine
      It serves the console at http://localhost:8787/server.html
      Override the port with SWEK_PORT=9000 swek-engine
    EOS
  end

  test do
    assert_predicate libexec/"ai-bridge/server.js", :exist?
  end
end
`;
}

// generate from a LOCAL zip (computes the real sha256). The url is where that same
// zip will be downloadable from once published (a GitHub release asset URL).
async function generateFromZip({ zipPath, url, version, owner }) {
    if (!zipPath || !fs.existsSync(zipPath)) return { ok: false, error: "release zip not found: " + zipPath };
    let sha;
    try { sha = await sha256File(zipPath); } catch (e) { return { ok: false, error: "sha256 failed: " + (e && e.message || e) }; }
    const ver = version || _verFromZipName(zipPath) || "0";
    const dlUrl = url || `https://github.com/${owner || "HowdyKeith"}/SweK-Engine/releases/download/v${String(ver).replace(/^v/, "")}/EngineProject_v${String(ver).replace(/^v/, "")}.zip`;
    const text = formulaText({ version: ver, url: dlUrl, sha256: sha, owner });
    return {
        ok: true,
        version: ver,
        sha256: sha,
        url: dlUrl,
        formula: text,
        formulaFileName: "swek-engine.rb",
        tap: (owner || "HowdyKeith").toLowerCase() + "/swek",
        installCommands: [
            "brew tap " + (owner || "HowdyKeith").toLowerCase() + "/swek",
            "brew install swek-engine",
        ],
        // the one-time publishing steps the engine can't silently do for you
        publishSteps: [
            "1. Publish the release: create a GitHub release tagged v" + String(ver).replace(/^v/, "") + " on " + (owner || "HowdyKeith") + "/SweK-Engine and upload EngineProject_v" + String(ver).replace(/^v/, "") + ".zip as an asset (the engine's GitHub panel can do this).",
            "2. Create a PUBLIC repo named '" + (owner || "HowdyKeith") + "/homebrew-swek'.",
            "3. Commit the generated swek-engine.rb into a 'Formula/' folder in that repo.",
            "4. From any Mac: " + "brew tap " + (owner || "HowdyKeith").toLowerCase() + "/swek && brew install swek-engine",
        ],
    };
}

function _verFromZipName(p) {
    const m = String(p).match(/(?:SweK_Engine|EngineProject)_v(\d+)\.zip/i);   // v2871 - both names
    return m ? m[1] : null;
}

module.exports = { sha256File, formulaText, generateFromZip };
