// FILE: ai-bridge/objIO.js
// VERSION: v1 — round 282
//
// Minimal OBJ parser + writer for bridge-side mesh post-processing.
// Only handles what the asset pipeline produces: vertex positions (v)
// and triangle indices (f). Throws away normals, UVs, materials,
// groups — those get recomputed downstream anyway. CommonJS so the
// bridge can require() it (bridge is package.json type=commonjs).
//
// Parse: ASCII OBJ → { positions: Float32Array, indices: Uint32Array }
// Write: { positions, indices } → ASCII OBJ string
//
// Performance: streams the file as one big read, single-pass split.
// 200K-vert OBJ parses in ~50ms on a typical CPU — fine for the
// post-processing pipeline.

const fs = require("fs");

// Parse an OBJ text into positions + indices. Skips lines we don't
// care about (normals, UVs, materials, group/object markers, comments).
// f lines:
//   f 1 2 3                          → 3 indices, 0-based after -1
//   f 1/2 3/4 5/6                    → same, ignore UV index
//   f 1//2 3//4 5//6                 → same, ignore normal index
//   f 1/2/3 4/5/6 7/8/9              → same, ignore both
//   f 1 2 3 4                        → quad, fan-triangulate to 1-2-3 + 1-3-4
// All face index references are 1-based in OBJ; we subtract 1.
function parseObj(text) {
    const positions = [];
    const indices   = [];
    const lines = text.split(/\r?\n/);
    for (let li = 0; li < lines.length; li++) {
        const line = lines[li];
        if (!line || line.charCodeAt(0) === 35) continue;     // empty / comment '#'
        // Quick reject for non-v/f lines (most common skips: vn, vt, mtllib, o, g, s, usemtl)
        const c0 = line.charCodeAt(0);
        if (c0 === 118) {     // 'v'
            // Only "v " (not vn/vt). Token-split on whitespace.
            if (line.charCodeAt(1) !== 32 && line.charCodeAt(1) !== 9) continue;
            const parts = line.split(/\s+/);
            if (parts.length < 4) continue;
            positions.push(+parts[1], +parts[2], +parts[3]);
        } else if (c0 === 102) {    // 'f'
            if (line.charCodeAt(1) !== 32 && line.charCodeAt(1) !== 9) continue;
            const parts = line.trim().split(/\s+/);
            // parts[0] is "f"; parts[1..] are vertex refs
            const verts = [];
            for (let i = 1; i < parts.length; i++) {
                const ref = parts[i];
                if (!ref) continue;
                // First "/"-delimited token is the position index
                const slash = ref.indexOf("/");
                const posIdxStr = slash >= 0 ? ref.slice(0, slash) : ref;
                const idx = parseInt(posIdxStr, 10);
                if (!Number.isFinite(idx)) continue;
                verts.push(idx - 1);    // OBJ is 1-based
            }
            if (verts.length < 3) continue;
            // Fan-triangulate quads / n-gons
            for (let i = 1; i < verts.length - 1; i++) {
                indices.push(verts[0], verts[i], verts[i + 1]);
            }
        }
    }
    return {
        positions: Float32Array.from(positions),
        indices:   Uint32Array.from(indices),
    };
}

function parseObjFile(filePath) {
    return parseObj(fs.readFileSync(filePath, "utf8"));
}

// Write positions + indices (+ optional normals) to OBJ format. Returns
// a string suitable for `fs.writeFileSync`. Output is human-readable
// with each vertex / normal / face on its own line.
function writeObj({ positions, indices, normals = null }) {
    const lines = [];
    lines.push("# generated by ai-bridge/objIO.js — round 282 post-processed mesh");
    const N = positions.length / 3;
    for (let i = 0; i < N; i++) {
        lines.push(`v ${positions[i * 3].toFixed(6)} ${positions[i * 3 + 1].toFixed(6)} ${positions[i * 3 + 2].toFixed(6)}`);
    }
    if (normals && normals.length === positions.length) {
        for (let i = 0; i < N; i++) {
            lines.push(`vn ${normals[i * 3].toFixed(6)} ${normals[i * 3 + 1].toFixed(6)} ${normals[i * 3 + 2].toFixed(6)}`);
        }
    }
    const T = indices.length / 3;
    if (normals && normals.length === positions.length) {
        // f v//vn — same vertex index for position and normal
        for (let i = 0; i < T; i++) {
            const a = indices[i * 3] + 1;
            const b = indices[i * 3 + 1] + 1;
            const c = indices[i * 3 + 2] + 1;
            lines.push(`f ${a}//${a} ${b}//${b} ${c}//${c}`);
        }
    } else {
        for (let i = 0; i < T; i++) {
            const a = indices[i * 3] + 1;
            const b = indices[i * 3 + 1] + 1;
            const c = indices[i * 3 + 2] + 1;
            lines.push(`f ${a} ${b} ${c}`);
        }
    }
    return lines.join("\n") + "\n";
}

module.exports = { parseObj, parseObjFile, writeObj };
