// simulation/tomo/iterative.js -- a reconstructor that believes something.
//
// Filtered back-projection is a way of thinking with no beliefs in it. That is its virtue and its ceiling. It
// cannot be wrong about the world because it says nothing about the world: it only redistributes what was actually
// measured. Hand it a direction it never looked in and it has nothing to offer -- which is why v2479 found that an
// eye choosing views by curiosity LOSES to one that plods evenly round the circle. Coverage was the requirement
// because the reasoning had no other way to fill a gap.
//
// This file is the other kind. It solves A x = b by iteration, and where the data runs out it falls back on a
// belief about what worlds are plausible. Two things follow, and the second is the interesting one:
//
//   1. It handles UNEVEN view sets natively. FBP scales by pi/nAngles -- it assumes an even spread and is simply
//      wrong otherwise. SIRT never assumes it; it just asks which image is consistent with the rays it was given.
//   2. With few views the problem is UNDERDETERMINED -- many images fit the data exactly. Something must choose
//      among them, and that something is the prior. Here it is total variation: prefer the image with the least
//      total edge. That is a real belief about the world ("it is made of regions, not noise"), it is a belief that
//      can be WRONG, and it is what buys the right to look selectively.
//
// THE TRAP THIS FILE DOES NOT FALL INTO. b is the ANALYTIC shadow -- the closed-form Radon transform -- never a
// projection generated by the A below. Generating the data with your own forward model is the inverse crime: the
// solver converges beautifully onto whatever your discretisation believes and proves nothing about the world. It is
// the v2455 self-reference trap and the backend-envelope trap in one costume. Because b is analytic and A is only
// a model of it, they disagree, and that disagreement is a FLOOR: measured at 0.303% on a 48^2 grid with 200 line
// samples (i.e. even handed the perfect answer, A reproduces reality only that well). No solver beats its own floor.
//
// WHAT THIS ROUND MEASURED (v2480), because the results are not what was predicted:
//
//   1. MOST OF THE GAIN IS NOT THE PRIOR. Plain SIRT with NO belief at all beats FBP eighteen-fold at four views
//      (178.22% -> 9.79%). That is pure geometry: FBP scales by pi/nAngles and is simply wrong on an uneven set,
//      while SIRT only asks which image fits the rays it was given. Solving the right problem beat believing things.
//
//   2. A FALSE BELIEF COSTS. Sweeping the TV weight at 8 views: 0 -> 5.74%, 0.0005 -> 5.45%, 0.002 -> 5.62%,
//      0.008 -> 12.34%, 0.03 -> 33.50%. A little TV helps (it suppresses streaks; blob interiors are locally flat
//      enough for that to be slightly true) and a lot of it is a disaster, because TV believes the world is flat
//      regions divided by sharp EDGES and the wax has no edges anywhere. FBP could not be wrong about the world
//      because it said nothing about the world. This can be wrong, and past 0.008 it is.
//
//   3. AND THE EYE IS RESCUED, BUT ONLY WHERE LOOKING IS EXPENSIVE. v2479 found curiosity loses to plodding 2-3x
//      under FBP. Under SIRT, at FOUR views, curiosity WINS in every world tried: a row of blobs 9.79% -> 8.67%,
//      a scattered clump 7.06% -> 5.55%, two blobs far apart 12.54% -> 7.45%. By six views uniform takes the lead
//      back in the crowded worlds -- but NOT in the sparsest one (5.69% -> 3.57%, active still ahead by 37%).
//
//      THE SPARSER THE WORLD, THE MORE A CHOSEN LOOK IS WORTH. Which is exactly what Keith said before any of this
//      was built: a flattened speck of a view "would not even register, unless there was less of it".
"use strict";

// A: what would this image cast as a shadow at angle theta?
function project(img, n, theta, nDet, S = 200) {
    const out = new Float64Array(nDet), ct = Math.cos(theta), st = Math.sin(theta);
    for (let i = 0; i < nDet; i++) {
        const s = -1 + (i + 0.5) * 2 / nDet;
        let acc = 0;
        for (let k = 0; k < S; k++) {
            const t = -1 + (k + 0.5) * 2 / S;
            const x = s * ct - t * st, y = s * st + t * ct;
            const fx = (x + 1) * n / 2 - 0.5, fy = (y + 1) * n / 2 - 0.5;
            const i0 = Math.floor(fx), j0 = Math.floor(fy);
            if (i0 < 0 || j0 < 0 || i0 + 1 >= n || j0 + 1 >= n) continue;
            const a = fx - i0, b = fy - j0;
            acc += ((img[j0*n+i0]*(1-a) + img[j0*n+i0+1]*a) * (1-b)
                  + (img[(j0+1)*n+i0]*(1-a) + img[(j0+1)*n+i0+1]*a) * b) * (2 / S);
        }
        out[i] = acc;
    }
    return out;
}

// A-transpose: smear a residual shadow back over the image. The ADJOINT of project -- it must use the same weights,
// or the iteration is descending a gradient that belongs to a different problem.
function backProject(resid, n, theta, nDet, out, S = 200) {
    const ct = Math.cos(theta), st = Math.sin(theta);
    for (let i = 0; i < nDet; i++) {
        const s = -1 + (i + 0.5) * 2 / nDet, r = resid[i];
        if (r === 0) continue;
        for (let k = 0; k < S; k++) {
            const t = -1 + (k + 0.5) * 2 / S;
            const x = s * ct - t * st, y = s * st + t * ct;
            const fx = (x + 1) * n / 2 - 0.5, fy = (y + 1) * n / 2 - 0.5;
            const i0 = Math.floor(fx), j0 = Math.floor(fy);
            if (i0 < 0 || j0 < 0 || i0 + 1 >= n || j0 + 1 >= n) continue;
            const a = fx - i0, b = fy - j0, w = r * (2 / S);
            out[j0*n+i0]       += w * (1-a) * (1-b);
            out[j0*n+i0+1]     += w * a * (1-b);
            out[(j0+1)*n+i0]   += w * (1-a) * b;
            out[(j0+1)*n+i0+1] += w * a * b;
        }
    }
}

// THE PRIOR, made explicit: the gradient of total variation. This is the belief that the world is made of regions
// rather than speckle. It is a claim about worlds, it can be false, and it is the entire reason this reconstructor
// can say anything about a direction it never measured.
function tvGradient(img, n, out, eps = 1e-6) {
    const at = (i, j) => img[Math.min(n-1, Math.max(0, j)) * n + Math.min(n-1, Math.max(0, i))];
    for (let j = 0; j < n; j++) for (let i = 0; i < n; i++) {
        const c = at(i, j);
        let g = 0;
        for (const [di, dj] of [[1,0],[-1,0],[0,1],[0,-1]]) {
            const d = c - at(i+di, j+dj);
            g += d / Math.sqrt(d*d + eps);
        }
        out[j*n+i] += g;
    }
}

// THE OTHER PRIOR: smoothness (Tikhonov). Penalise the SQUARE of the gradient rather than its magnitude.
// The difference is entirely in what each believes about edges. TV's |grad| is cheap to cross once and expensive to
// cross gently, so it builds worlds of flat plateaus with sharp cliffs -- which is why it wins on a bone-and-tissue
// scan and loses on wax. Tikhonov's |grad|^2 punishes any sharp jump enormously, so it believes the world varies
// gently everywhere. THAT is what the blobulator actually is. Same machinery, opposite claim about reality.
function smoothGradient(img, n, out) {
    const at = (i, j) => img[Math.min(n-1, Math.max(0, j)) * n + Math.min(n-1, Math.max(0, i))];
    for (let j = 0; j < n; j++) for (let i = 0; i < n; i++) {
        const c = at(i, j);
        // the gradient of sum |grad x|^2 is the (negative) Laplacian
        out[j*n+i] += 4 * c - at(i+1, j) - at(i-1, j) - at(i, j+1) - at(i, j-1);
    }
}

// SIRT with an optional total-variation prior. tvWeight = 0 gives a belief-free least-squares solve, which is
// already better than FBP on an uneven view set -- the prior is a SEPARATE question from handling uneven angles.
function reconstructIterative(sino, n, { iters = 60, step = 0.9, tvWeight = 0, smoothWeight = 0, nonNeg = true } = {}) {
    const { data, angles, nAngles, nDet } = sino;
    const img = new Float64Array(n * n);
    // SIRT normalisation: how much total weight lands on each pixel, so a pixel seen by many rays is not shouted at
    const ones = new Float64Array(nDet).fill(1);
    const colSum = new Float64Array(n * n);
    for (let j = 0; j < nAngles; j++) backProject(ones, n, angles[j], nDet, colSum);
    for (let i = 0; i < colSum.length; i++) if (colSum[i] < 1e-8) colSum[i] = 1e-8;

    const grad = new Float64Array(n * n);
    for (let it = 0; it < iters; it++) {
        grad.fill(0);
        for (let j = 0; j < nAngles; j++) {
            const th = angles[j], pred = project(img, n, th, nDet);
            const resid = new Float64Array(nDet);
            for (let i = 0; i < nDet; i++) resid[i] = data[j*nDet + i] - pred[i];
            backProject(resid, n, th, nDet, grad);
        }
        for (let i = 0; i < grad.length; i++) img[i] += step * grad[i] / colSum[i];
        if (tvWeight > 0) {
            const tg = new Float64Array(n * n);
            tvGradient(img, n, tg);
            for (let i = 0; i < img.length; i++) img[i] -= tvWeight * tg[i];
        }
        if (smoothWeight > 0) {
            const sg = new Float64Array(n * n);
            smoothGradient(img, n, sg);
            for (let i = 0; i < img.length; i++) img[i] -= smoothWeight * sg[i];
        }
        if (nonNeg) for (let i = 0; i < img.length; i++) if (img[i] < 0) img[i] = 0;   // density is not negative
    }
    return img;
}
export { project, backProject, tvGradient, smoothGradient, reconstructIterative };
