// FILE: tools/media/makeStageClip.mjs -- v4193
//
// Generates media/stage.af: a short green-screen clip, encoded with WebCodecs in a real browser and packed
// with media/afContainer.mjs.
//
// *** THE CLIP IS THE ENGINE'S OWN OUTPUT, NOT FOOTAGE FROM SOMEWHERE. *** Under v4186's posture a vendored
// clip would need its own licence provenance, and a stock video of a person on a green screen is exactly the
// kind of asset that arrives with none. Drawing the scene here means the test input is SweK's own, the whole
// loop is inside the tree, and the file can be regenerated by anyone from this script rather than trusted.
//
// The scene is chosen to be the two pixels render/chromaKeyModel.mjs was designed around and could previously
// only be shown a painted rectangle of: a SHADOWED FOLD of the same cloth, and a BLOWN HIGHLIGHT. Plus a
// subject that walks (so successive frames really differ, which is what makes the inter-frame samples real),
// dark eyes for the dark-floor case, and a green spill rim for despill.
//
// *** AND THE FILE IS THE FIXTURE, NOT THIS SCRIPT -- WHICH IS THE OPPOSITE OF v4190. ***
//
// audio/sfxModel.mjs renders a sound from a parameter block, so the ARTEFACT can be thrown away and re-derived
// byte-for-byte; the generator is the source of truth. A video encoder is not like that. Measured here: two
// runs of this script over the SAME 60 drawn frames produced 32,996 and 32,957 bytes, differing in 98.2% of
// them. VP8's rate control and threading are not deterministic, so re-encoding is not a no-op.
//
// What IS reproducible is the thing that matters: once committed, media/stage.af decodes to identical frames
// on every run and in every process -- verified, seeking to frame 47 and playing forward to it both give
// 33f75fe3, twice, in two separate processes. So `--write` REPLACES the fixture rather than refreshing it,
// and is a deliberate act: any hash recorded against the old clip is about the old clip.
//
// Needs a browser: node has no VideoEncoder. Run: node tools/media/makeStageClip.mjs [--write]
"use strict";

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { pack, describe, unpack } from "../../media/afContainer.mjs";

const ENG = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..");
export const CLIP_PATH = path.join(ENG, "media", "stage.af");

/** Everything the page does, as a string, so the scene lives in one place and is readable here. */
export const SCENE = `(W, H, x, f, N) => {
    const t = f / N;
    x.fillStyle = "rgb(13,191,38)"; x.fillRect(0, 0, W, H);                       // lit cloth
    x.fillStyle = "rgb(5,77,15)";   x.fillRect(0, H * 0.62, W, H * 0.38);         // a shadowed fold of it
    x.fillStyle = "rgb(51,242,82)"; x.fillRect(W * 0.76, 0, W * 0.24, H * 0.28);  // a blown highlight on it
    const cx = W * (0.20 + 0.55 * t);                                             // the subject, walking
    x.fillStyle = "rgb(217,173,153)"; x.fillRect(cx - 30, H * 0.24, 60, H * 0.56);
    x.fillStyle = "rgb(8,8,9)";                                                   // eyes: the dark-floor case
    x.fillRect(cx - 16, H * 0.34, 9, 9); x.fillRect(cx + 7, H * 0.34, 9, 9);
    x.fillStyle = "rgb(140,184,79)"; x.fillRect(cx - 30, H * 0.52, 60, 10);       // a green spill rim
}`;

export const SETTINGS = Object.freeze({ width: 256, height: 256, frames: 60, gop: 15, codec: "vp8", bitrate: 900000, fps: 30 });

/** Encode in a browser and return the samples. `launch` supplies a Playwright-like browser. */
export async function encodeWithBrowser(launch, url) {
    const browser = await launch();
    const pg = await browser.newPage();
    await pg.goto(url, { waitUntil: "domcontentloaded" });
    const chunks = await pg.evaluate(async ({ S, sceneSrc }) => {
        const draw = eval("(" + sceneSrc + ")");
        const cv = document.createElement("canvas"); cv.width = S.width; cv.height = S.height;
        const x = cv.getContext("2d");
        const sup = await VideoEncoder.isConfigSupported({ codec: S.codec, width: S.width, height: S.height, bitrate: S.bitrate, framerate: S.fps });
        if (!sup.supported) throw new Error(`this browser cannot encode ${S.codec}`);
        const out = [];
        const enc = new VideoEncoder({
            output: (c) => { const d = new Uint8Array(c.byteLength); c.copyTo(d); out.push({ ts: c.timestamp, key: c.type === "key", data: Array.from(d) }); },
            error: (e) => { throw e; },
        });
        enc.configure({ codec: S.codec, width: S.width, height: S.height, bitrate: S.bitrate, framerate: S.fps });
        for (let f = 0; f < S.frames; f++) {
            draw(S.width, S.height, x, f, S.frames);
            const frame = new VideoFrame(cv, { timestamp: Math.round(f * 1e6 / S.fps) });
            enc.encode(frame, { keyFrame: f % S.gop === 0 });
            frame.close();
        }
        await enc.flush();
        enc.close();
        return out;
    }, { S: SETTINGS, sceneSrc: SCENE });
    await browser.close();
    return chunks.map((c) => ({ ts: c.ts, key: c.key, data: new Uint8Array(c.data) }));
}

/** Pack samples into the container, with a manifest that says where the footage came from. */
export function packClip(samples) {
    return pack({
        codec: SETTINGS.codec, width: SETTINGS.width, height: SETTINGS.height,
        frameCount: samples.length, timescale: 1000000,
        source: "generated by SweK: tools/media/makeStageClip.mjs",
        note: "a green-screen stage with a walking subject, a shadowed fold and a blown highlight",
    }, samples);
}

if (process.argv[1] && process.argv[1].endsWith("makeStageClip.mjs")) {
    if (!fs.existsSync(CLIP_PATH)) { console.log("media/stage.af is missing -- regenerate it with --write and a browser"); process.exit(0); }
    const cur = unpack(new Uint8Array(fs.readFileSync(CLIP_PATH)));
    console.log("current clip: " + describe(cur));
    console.log("source: " + cur.manifest.source);
    if (!process.argv.includes("--write")) { console.log("\n(pass --write with playwright installed to regenerate)"); process.exit(0); }
    // *** ESM IGNORES NODE_PATH, so a globally-installed playwright is not importable by name. *** Resolve it
    // through createRequire (which does honour the global paths) and import the file URL. A dev tool that
    // fails with "Cannot find package" when the package is plainly installed sends the next person hunting.
    const { chromium } = await (async () => {
        try { const m = await import("playwright"); if (m.chromium || (m.default && m.default.chromium)) return m.chromium ? m : m.default; } catch {}
        try {
            const { createRequire } = await import("node:module");
            const req = createRequire(import.meta.url);
            // resolve() takes the search paths as an OPTION; `require.paths` is not a thing (module.paths is,
            // on a Module, and this is a require function). Getting that wrong reports "Cannot read properties
            // of undefined", which names neither playwright nor the real mistake.
            const globals = ["/opt/node22/lib/node_modules", "/usr/lib/node_modules", "/usr/local/lib/node_modules",
                             ...(process.env.NODE_PATH ? process.env.NODE_PATH.split(":") : [])];
            const { pathToFileURL } = await import("node:url");
            const mod = await import(pathToFileURL(req.resolve("playwright", { paths: globals })).href);
            // playwright is CommonJS, so import() hangs its exports off .default -- destructuring the
            // namespace directly yields undefined and the failure names `launch`, not the interop.
            return mod.chromium ? mod : mod.default;
        } catch (e) {
            console.error("makeStageClip: playwright is not resolvable from here (" + e.message + ").\n" +
                          "  Install it, or run with:  node --experimental-loader ... , or set NODE_PATH and use require.");
            process.exit(1);
        }
    })();
    const samples = await encodeWithBrowser(
        () => chromium.launch({ executablePath: "/opt/pw-browsers/chromium" }),
        process.env.SWEK_CLIP_URL || "http://127.0.0.1:8737/sfx.html");
    const buf = packClip(samples);
    console.log("\n*** --write REPLACES the fixture. *** A video encoder is not deterministic (measured: two runs\n" +
                "    over the same frames differed in 98.2% of their bytes), so this is a new clip, not the old one\n" +
                "    refreshed. Anything hashed against the previous file is now about a file that no longer exists.");
    fs.writeFileSync(CLIP_PATH, buf);
    console.log("wrote " + CLIP_PATH + "\n" + describe(unpack(buf)));
}
