// WebGLEngine/tools/ship/buildEngineCatalog.mjs -- v4040
// ---------------------------------------------------------------------------------------------------------------
// REGENERATES engine-catalog.json's `builtinDemos` FROM main.js's live DEMO_MODES array. NOTHING DID THIS BEFORE.
//
// Keith asked how many demos/built-ins the orange "Demo:" pill on index.html lists. Counting them turned up a
// real bug rather than just an answer: engine-catalog.json says `builtinDemos: 58` and is dated three days
// before the main.js it claims to be "generatedFrom" -- and a repo-wide search for who WRITES that field found
// NOTHING. It is not stale from neglect this round; it has apparently never been regenerated by anything, ever.
// tools/ship/launchIndex.mjs's own header even says the number ("58 inline DEMO_MODES") as a comment, which is
// the exact "declared, not derived" shape this tree keeps finding and removing elsewhere -- just one level
// removed, since here the STALE FILE is what got declared into a comment rather than a number typed by hand.
//
// MEASURED: main.js's DEMO_MODES array literal, parsed directly from source right now, has 42 entries -- 16
// fewer than the file claims. launch-index.json's "54 built-ins" (after launchIndex.mjs's own dedup against
// pages) is downstream of that same stale 58 and is wrong by the same margin, and so is anything a reader
// concludes from it.
//
// *** WHY THIS PARSES SOURCE TEXT RATHER THAN EVALUATING THE ARRAY. *** DEMO_MODES entries carry real functions
// (start/stop/tick) that close over module-scope helpers defined elsewhere in main.js. `new Function("return "+
// arrayText)()` would either throw on those free references or -- worse -- silently succeed today and become a
// ship-time code-execution surface the day an entry's construction-time (not call-time) code references
// something that fails, or something that has a side effect. A build step has no business running arbitrary
// application code to count an array. So this reads id/label out of the SOURCE TEXT with a small, honest lexer,
// the same way tools/ship/sourceScan.mjs's whole existence argues for: regexAllowedHere()/regexBody() are
// IMPORTED from there rather than re-invented, because a regex literal inside a demo's tick() body (a real
// pattern in this file, e.g. a `.replace(/[{}]/g, ...)`) contains brace-shaped characters that would corrupt a
// depth counter that did not know to skip over it -- exactly the "179 files mis-lexed" bug that file's own
// header is about, here at one remove.
//
// WHAT THIS DOES NOT DO: touch `apps` (the Applications-pill entries) or `generatedFrom`. Those are untouched by
// this bug and untouched by this file -- rewriting a field nobody asked about, while fixing the one that is
// actually broken, is the kind of "helpful" edit that turns one verified fix into two unverified ones.
// ---------------------------------------------------------------------------------------------------------------
"use strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { regexAllowedHere, regexBody } from "./sourceScan.mjs";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ENG = path.resolve(HERE, "..", "..");

/** Index just past the comment/string/regex-literal starting at src[i], or null if i is not the start of one. */
function skipTrivia(src, i, out) {
    const c = src[i], d = src[i + 1];
    if (c === "/" && d === "/") { let j = i + 2; while (j < src.length && src[j] !== "\n") j++; return j; }
    if (c === "/" && d === "*") { let j = i + 2; while (j < src.length && !(src[j] === "*" && src[j + 1] === "/")) j++; return Math.min(j + 2, src.length); }
    if (c === "'" || c === '"' || c === "`") return stringLiteral(src, i).end;
    if (c === "/" && regexAllowedHere(out)) { const r = regexBody(src, i); if (r) return r.end; }
    return null;
}

/** src[i] is a quote character. Returns the RAW content between the quotes (escapes not decoded, beyond the
 *  handful unescapeBasic() below handles for display) and the index just past the closing quote. */
function stringLiteral(src, i) {
    const q = src[i];
    let j = i + 1;
    while (j < src.length && src[j] !== q) { if (src[j] === "\\") j++; j++; }
    return { value: src.slice(i + 1, j), end: Math.min(j + 1, src.length) };
}

// v4040 -- FIRST BUG THIS FILE'S OWN TEST CAUGHT: a bare `\X -> X` fallback ate the "u" off `—`, turning
// an em dash into the literal text "u2014" in "ARCHITECTURE — system diagram" -- decoded silently wrong,
// which is worse than not decoding at all. \uXXXX is matched and decoded FIRST, so the generic single-char
// fallback below only ever sees escapes that really are one character (\\, \", \', \n, \t, \r, ...).
function unescapeBasic(s) {
    return s.replace(/\\u([0-9a-fA-F]{4})/g, (m, hex) => String.fromCharCode(parseInt(hex, 16)))
            .replace(/\\(.)/g, (m, c) => (c === "n" ? "\n" : c === "t" ? "\t" : c === "r" ? "\r" : c));
}

/** Find the index of the bracket that closes the opener at src[openIdx] ('{', '[' or '('), skipping trivia. */
function matchClose(src, openIdx) {
    const OPEN = "{[(", CLOSE = "}])";
    let depth = 0, i = openIdx, out = "";
    while (i < src.length) {
        const c = src[i];
        const triv = skipTrivia(src, i, out);
        if (triv != null) { out += src.slice(i, triv); i = triv; continue; }
        if (OPEN.includes(c)) depth++;
        else if (CLOSE.includes(c)) { depth--; if (depth === 0) return i; }
        out += c; i++;
    }
    return -1;
}

/** Every top-level `{...}` object between src[from] and src[to), as raw text spans. */
function splitTopLevelObjects(src, from, to) {
    const objs = [];
    let i = from, out = "";
    while (i < to) {
        const c = src[i];
        const triv = skipTrivia(src, i, out);
        if (triv != null) { out += src.slice(i, triv); i = triv; continue; }
        if (c === "{") {
            const close = matchClose(src, i);
            if (close < 0) break;
            objs.push(src.slice(i, close + 1));
            out += src.slice(i, close + 1);
            i = close + 1;
            continue;
        }
        out += c; i++;
    }
    return objs;
}

/** The value of a TOP-LEVEL (depth 1, i.e. a direct property of objText's own leading '{') `field: "..."`, or
 *  null. Depth-tracked so a decoy `label` on a NESTED object (objText carries several -- kaijuSim, controls,
 *  padControls all define their own) is never mistaken for this entry's own. */
function extractField(objText, field) {
    const n = objText.length;
    let i = 0, depth = 0, out = "";
    while (i < n) {
        const c = objText[i];
        const triv = skipTrivia(objText, i, out);
        if (triv != null) { out += objText.slice(i, triv); i = triv; continue; }
        if ("{[(".includes(c)) { depth++; out += c; i++; continue; }
        if ("}])".includes(c)) { depth--; out += c; i++; continue; }
        if (depth === 1 && /[A-Za-z_$]/.test(c) && objText.startsWith(field, i)) {
            const before = objText[i - 1];
            const after = objText[i + field.length];
            const wholeWord = (before === undefined || !/[A-Za-z0-9_$]/.test(before)) &&
                               (after === undefined || !/[A-Za-z0-9_$]/.test(after));
            if (wholeWord) {
                let j = i + field.length;
                while (j < n && /\s/.test(objText[j])) j++;
                if (objText[j] === ":") {
                    j++;
                    while (j < n && /\s/.test(objText[j])) j++;
                    if (objText[j] === "'" || objText[j] === '"' || objText[j] === "`") {
                        return unescapeBasic(stringLiteral(objText, j).value);
                    }
                }
            }
        }
        // not a field match at this position: skip the whole identifier so each letter isn't re-tested
        if (/[A-Za-z_$]/.test(c)) {
            let k = i; while (k < n && /[A-Za-z0-9_$]/.test(objText[k])) k++;
            out += objText.slice(i, k); i = k; continue;
        }
        out += c; i++;
    }
    return null;
}

/**
 * The whole point: DEMO_MODES's entries, as {id, label}, read from main.js's SOURCE TEXT. Returns null if the
 * array marker or its closing bracket cannot be found (a caller should treat that as "could not parse", never
 * as "zero entries" -- the two are different facts, and the difference is exactly what let this go stale
 * silently for three days: nothing distinguished "the array is empty" from "nothing read the array at all".
 */
export function parseDemoModes(src) {
    const marker = "const DEMO_MODES = [";
    const markerIdx = src.indexOf(marker);
    if (markerIdx < 0) return null;
    const openIdx = markerIdx + marker.length - 1;
    const closeIdx = matchClose(src, openIdx);
    if (closeIdx < 0) return null;
    const objs = splitTopLevelObjects(src, openIdx + 1, closeIdx);
    const out = [];
    for (const t of objs) {
        const id = extractField(t, "id");
        if (!id) continue;   // an entry with no id is not a launchable demo; extractField already ignored nested decoys
        const label = extractField(t, "label");
        out.push({ id, label: label || id });
    }
    return out;
}

function main() {
    const mainJs = fs.readFileSync(path.join(ENG, "main.js"), "utf8");
    const demos = parseDemoModes(mainJs);
    if (demos === null) {
        console.error("[engineCatalog] could not find DEMO_MODES in main.js -- catalog NOT written (a parse failure must not silently produce an empty list)");
        process.exitCode = 1;
        return;
    }
    const catPath = path.join(ENG, "engine-catalog.json");
    let cat = {};
    try { cat = JSON.parse(fs.readFileSync(catPath, "utf8")); } catch { cat = { generatedFrom: "main.js", apps: [] }; }
    const before = Array.isArray(cat.builtinDemos) ? cat.builtinDemos.length : null;
    cat.builtinDemos = demos;
    fs.writeFileSync(catPath, JSON.stringify(cat, null, 2) + "\n");
    console.log(`[engineCatalog] builtinDemos: ${before ?? "(none)"} -> ${demos.length}` +
        (before !== null && before !== demos.length ? "  *** COUNT CHANGED ***" : ""));
}

if (import.meta.url === pathToFileURL(process.argv[1] || "").href) main();
