// tools/ship/corpus.mjs
//
// Run: node tools/ship/corpus.mjs           (report what a corpus would contain)
//      node tools/ship/corpus.mjs --write   (emit WebGLEngine/corpus.txt)
//
// v3099 -- A RESEARCH AGENT NEEDS TEXT, AND THE DASHBOARD IS NOT TEXT.
//
// Keith, working out why local-deep-researcher pointed at server.html would not work: "server.html is a live
// dashboard -- it renders from API calls at runtime, so a crawler fetching it gets an empty shell with a script
// tag." That is exactly right and it is worth a number. MEASURED: server.html is 480,729 bytes and yields
// 17,937 bytes after script, style and tags are stripped -- 3.7% -- and what survives is menu labels and button
// captions. A crawler pointed at it reads a navigation bar.
//
// Meanwhile BACKLOG.md is 2,097,347 bytes of prose about why every decision was made. THE TEXT WAS NEVER
// MISSING; it was never SERVED as text. This assembles the sources Keith named -- the changelog, the knowledge
// index, the claim ledger -- into one plain file a crawler can actually read.
//
// SERVED, NOT JUST WRITTEN. --write emits into WebGLEngine/, which the bridge already serves statically, so the
// artifact has a URL (http://host:8787/corpus.txt) rather than being a file somebody has to know to look for.
// EVERY TOOL NEEDS A FRONT DOOR, and for a thing whose entire purpose is to be fetched, the front door IS the
// URL -- a page rendering it would be the dashboard problem again.
//
// WHAT IT DELIBERATELY DOES NOT DO: no summarising, no ranking, no "relevant excerpts". A research agent does
// its own reading; a corpus that pre-decided what mattered would be answering the question it was fetched to
// help with. It concatenates, labels the provenance of each block, and stops.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ENG = path.resolve(HERE, "..", "..");
const ROOT = path.resolve(ENG, "..");

const readOr = (p, fallback = "") => { try { return fs.readFileSync(p, "utf8"); } catch { return fallback; } };

/**
 * How much of a file is text a crawler would actually get? Strips script and style ELEMENTS (not just tags --
 * their contents are the point), then all remaining markup. Returns bytes and the ratio.
 *
 * This is the measurement that makes the case, and it is applied to the corpus itself as well as to the
 * dashboard, because a corpus that scored badly here would be the same failure with a different filename.
 */
export function textYield(src) {
    const stripped = String(src)
        .replace(/<script[\s\S]*?<\/script>/gi, " ")
        .replace(/<style[\s\S]*?<\/style>/gi, " ")
        .replace(/<[^>]+>/g, " ")
        .replace(/\s+/g, " ")
        .trim();
    return { bytes: String(src).length, text: stripped.length, ratio: String(src).length ? stripped.length / String(src).length : 0 };
}

/** The sources, each with WHY it is in here. A block with no stated reason is a block nobody can prune later. */
export function corpusSources() {
    return [
        { id: "changelog", file: path.join(ROOT, "BACKLOG.md"),
          why: "the reasoning behind every version -- what was tried, what it measured, and what was rejected. " +
               "The largest body of prose in the project and the only place the NEGATIVE results live." },
        { id: "todo", file: path.join(ROOT, "TODO.md"),
          why: "one line per version saying what the next person needs to know, which is the index into the above." },
        { id: "knowledge-index", file: path.join(ENG, "knowledge-index.json"),
          why: "the derived map of gates and claims -- what the tree checks and what it asserts, machine-built." },
        { id: "status", file: path.join(ROOT, "STATUS.md"),
          why: "the regenerated snapshot of where the build stands." },
        { id: "session-start", file: path.join(ROOT, "SESSION_START.md"),
          why: "the standing rules a newcomer is expected to read first." },
    ];
}

export function buildCorpus() {
    const blocks = [], missing = [];
    for (const s of corpusSources()) {
        const raw = readOr(s.file, null);
        if (raw === null) { missing.push(s.id); continue; }
        blocks.push(
            "=".repeat(78) + "\n" +
            "SOURCE: " + s.id + "\n" +
            "FILE:   " + path.relative(ROOT, s.file).replace(/\\/g, "/") + "\n" +
            "WHY:    " + s.why + "\n" +
            "BYTES:  " + raw.length + "\n" +
            "=".repeat(78) + "\n\n" + raw.trim() + "\n");
    }
    const header =
        "SweK Engine -- text corpus for research agents\n" +
        "Generated by tools/ship/corpus.mjs. Plain text on purpose: server.html is a live dashboard and yields\n" +
        "about 3.7% text to a crawler, nearly all of it button captions. Everything below is prose or derived\n" +
        "data, each block labelled with where it came from and why it is included.\n" +
        "NOT summarised, NOT ranked, NOT excerpted -- a corpus that pre-decided what mattered would be answering\n" +
        "the question it was fetched to help with.\n\n";
    return { text: header + blocks.join("\n"), blocks: blocks.length, missing };
}

if (import.meta.url === pathToFileURL(process.argv[1] || "").href) {
    const { text, blocks, missing } = buildCorpus();
    const y = textYield(text);
    const dash = textYield(readOr(path.join(ENG, "server.html")));
    console.log("[corpus] " + blocks + " blocks, " + text.length + " bytes");
    console.log("[corpus] text yield " + (100 * y.ratio).toFixed(1) + "%  vs server.html " + (100 * dash.ratio).toFixed(1) + "%");
    if (missing.length) console.log("[corpus] MISSING (skipped, not faked): " + missing.join(", "));
    if (process.argv.includes("--write")) {
        const out = path.join(ENG, "corpus.txt");
        fs.writeFileSync(out, text);
        console.log("[corpus] wrote " + path.relative(ROOT, out).replace(/\\/g, "/") + " -- served at /corpus.txt");
    } else {
        console.log("[corpus] dry run. Add --write to emit WebGLEngine/corpus.txt");
    }
    process.exit(missing.length ? 1 : 0);
}
