#!/usr/bin/env node
// tools/ship/status.mjs — regenerate STATUS.md, the LIVING state of the project.
//
// SESSION_START.md is the protocol ("confirm version, work from the zip, never reuse a number"); STATUS.md is
// the *current state* a new session reads instead of reconstructing it from BACKLOG: what version is live,
// what shipped in the last few builds, and — subsuming the reflection-notes "rig-verify emission" item — the
// RIG-PENDING checklist auto-extracted from recent changelog entries (things Claude can't verify from the
// sandbox and Keith must confirm on his hardware). Run it as the last step of a ship so STATUS is never stale.
//
// USAGE (from WebGLEngine root or project root):
//   node tools/ship/status.mjs                       # regenerate; preserves the manual "## Next" block
//   node tools/ship/status.mjs --next /tmp/next.md   # regenerate + replace the "## Next" block from a file
import fs from "node:fs";
import path from "node:path";

function findAtRoot(name) { let d = process.cwd(); for (let i = 0; i < 5; i++) { const p = path.join(d, name); if (fs.existsSync(p)) return p; const up = path.dirname(d); if (up === d) break; d = up; } return null; }
function findEngine() { let d = process.cwd(); for (let i = 0; i < 6; i++) { const p = path.join(d, "WebGLEngine", "main.js"); if (fs.existsSync(p)) return p; if (fs.existsSync(path.join(d, "main.js")) && d.endsWith("WebGLEngine")) return path.join(d, "main.js"); const up = path.dirname(d); if (up === d) break; d = up; } return null; }
function arg(name) { const i = process.argv.indexOf(name); return i >= 0 ? process.argv[i + 1] : null; }

const backlogPath = findAtRoot("BACKLOG.md");
const statusPath = backlogPath ? path.join(path.dirname(backlogPath), "STATUS.md") : null;
const mainPath = findEngine();
if (!backlogPath || !statusPath) { console.error("[status] BACKLOG.md not found at project root"); process.exit(2); }

// current version
let version = "?";
try { version = (fs.readFileSync(mainPath, "utf8").match(/const ENGINE_VERSION = "(v\d+)"/) || [])[1] || "?"; } catch {}

// parse BACKLOG into version blocks
const backlog = fs.readFileSync(backlogPath, "utf8");
const blocks = [];
{
  const re = /^## (v\d+.*)$/gm; let m, last = null;
  while ((m = re.exec(backlog))) { if (last) last.end = m.index; last = { header: m[1].trim(), start: m.index + m[0].length }; blocks.push(last); }
  if (last) last.end = backlog.length;
}
function firstBullet(block) {
  const body = backlog.slice(block.start, block.end);
  const line = (body.split(/\r?\n/).find(l => /^\s*-\s*\[/.test(l)) || "").trim().replace(/^-\s*/, "");
  return line.replace(/\s+/g, " ").slice(0, 160);
}
const recent = blocks.slice(0, 6).map(b => `- **${b.header.split(/\s/)[0]}** — ${firstBullet(b)}`);

// rig-pending: scan the last ~10 version blocks for lines that describe an ACTIONABLE rig-only step
// (something Keith does on his box), not prose that merely mentions the sandbox/testability.
const RIG_RE = /(RIG-ONLY|rig-pending|first real (?:run|test|use)|npm install in|npm run once|stood? up on Galaxina|on Galaxina is (?:the )?first|test happens? on Keith|awaiting Keith|Keith (?:runs|installs|to test)|needs Keith's (?:box|rig|hardware|ear|eye))/i;
// skip lines that are validation notes / descriptions rather than a pending action
const SKIP_RE = /^(Validated|Unlike|RESULTS differ|checks?\.mjs \+ diff|[0-9]+ files)/i;
const rig = [];
for (const b of blocks.slice(0, 10)) {
  const body = backlog.slice(b.start, b.end);
  for (const raw of body.split(/\r?\n/)) {
    const line = raw.trim();
    if (line.length < 14 || !RIG_RE.test(line) || SKIP_RE.test(line)) continue;
    const clean = line.replace(/^[-*]\s*/, "").replace(/^\[[a-z,]+\]\s*/i, "").replace(/\s+/g, " ").slice(0, 200);
    const tag = b.header.split(/\s/)[0];
    if (!rig.some(r => r.text === clean)) rig.push({ tag, text: clean });
  }
}
const rigList = rig.slice(0, 14).map(r => `- [ ] (${r.tag}) ${r.text}`);

// preserve or replace the manual "## Next" block
let nextBlock = "- (nothing queued — see the tail of BACKLOG.md / TODO.md for candidates)";
const nextFile = arg("--next");
if (nextFile && fs.existsSync(nextFile)) nextBlock = fs.readFileSync(nextFile, "utf8").trim();
else if (fs.existsSync(statusPath)) {
  const cur = fs.readFileSync(statusPath, "utf8");
  const m = cur.match(/## Next\s*\n([\s\S]*?)(?:\n## |\s*$)/);
  if (m && m[1].trim()) nextBlock = m[1].trim();
}

const out = `# STATUS.md — SweK Engine current state

_Auto-generated by \`tools/ship/status.mjs\` on ${new Date().toISOString().slice(0, 10)}. This is the LIVE state;
read \`SESSION_START.md\` for the session protocol. Regenerated on every ship, so it should not be stale._

## Current version
**${version}** — the newest shipped build. Work forward from here; never reuse a version number (supersede forward).

## Recently shipped
${recent.join("\n")}

## Rig-pending (needs Keith's actual hardware — not verifiable from the sandbox)
These are auto-extracted from recent changelog entries. Claude builds them "correct by construction" but the
listed step happens on Keith's boxes (Galaxina = Windows+GPU, Stellar Atlas = Intel Mac). Check them off as done.
${rigList.length ? rigList.join("\n") : "- [ ] (none flagged in the recent window)"}

## Next
${nextBlock}
`;
fs.writeFileSync(statusPath, out);
console.log(`[status] wrote ${path.basename(statusPath)} — ${version}, ${recent.length} recent, ${rigList.length} rig-pending.`);
