// tools/ledger/subsystemSources.mjs
//
// Pure data: which source files back each fingerprint subsystem. Extracted from ledger.mjs (v2761) so that
// browser pages -- catalog.html via catalog.mjs -- can import this WITHOUT dragging in ledger's node:crypto,
// node:fs and node:path, which a browser cannot load. ledger.mjs re-exports it for its own callers.

export const SUBSYSTEM_SOURCES = {
    "strict-libm": ["tools/strictTrig.mjs", "tools/strictExpErf.mjs"],
    "md-forcefield": ["physics/md/md.js", "physics/md/bonds.js", "physics/md/angles.js"],
    "obb-collision": ["physics/obbOverlap.js", "physics/voxelPose.js"],
    "ewald-electrostatics": ["physics/md/ewald.js"],
    "prime-transport": ["brain/transport/primeTransport.js"],
    "astar-pathfinding": ["brain/astar/astar.js"],
    "xpbd-cloth": ["physics/xpbd/xpbd.js"],
    "tf-advect": ["brain/tf/tfStep.js"],
    "cloth-collision": ["physics/xpbd/clothMesh.js", "physics/xpbd/selfCollide.js", "physics/xpbd/clothStep.js"],
    "xpbd-damped": ["physics/xpbd/xpbdDamped.js"],
    "cloth-tear": ["physics/xpbd/tear.js"],
    "cloth-pinned": ["physics/xpbd/attach.js"],
    "thermal-cloth": ["physics/xpbd/modulate.js"],
    "plastic-cloth": ["physics/xpbd/plastic.js"],
    "muscle-actuator": ["physics/xpbd/muscle.js"],
    "fluid-mesh": ["physics/xpbd/fluid.js"],
    "pbf-fluid": ["physics/xpbd/pbf.js"],
    "fluid-pbf": ["physics/xpbd/fluid.js", "physics/xpbd/pbf.js"],
    "volume-balloon": ["physics/xpbd/volume.js"],
    "friction-slope": ["physics/xpbd/friction.js"],
    "friction-pile": ["physics/xpbd/frictionalContact.js"],
    "fluid-drag": ["physics/xpbd/fluid.js"],
    "cloth-anisotropy": ["physics/xpbd/anisotropy.js"],
    "pbf-polish": ["physics/xpbd/pbf.js"],
    "sampled-field": ["physics/xpbd/sampledField.js"],
    "wind-cloth": ["physics/xpbd/windCloth.js"],
    "muscle-belly": ["physics/xpbd/muscleVolume.js", "physics/xpbd/volume.js"],
    "thermal-diffusion": ["physics/strictGaussian.js", "tools/strictExpErf.mjs"],
    "centrifuge": ["physics/centrifuge.js"],
    "gyroscope": ["physics/gyroscope.js"],
    "pendulum-wave": ["physics/pendulumWave.js", "tools/strictTrig.mjs"],
    "orbit": ["physics/orbit.js"],
    "vibrations": ["physics/vibrations.js", "tools/strictTrig.mjs"],
    "fft": ["physics/fft.js", "tools/strictTrig.mjs"],
    "zeta": ["physics/zeta.js"],
    "zeta-critical": ["physics/zetaCritical.js", "tools/strictLog.mjs", "tools/strictTrig.mjs"],
    "figure-eight": ["physics/figureEight.js", "physics/orbit.js"],
    "lockstep": ["physics/lockstep.js", "physics/orbit.js", "tools/hash.mjs"],
    "black-hole": ["physics/blackHole.js"],
    "solar-system": ["physics/solarSystem.js", "physics/orbit.js"],
    "neutron-star": ["physics/neutronStar.js", "physics/blackHole.js"],
    "plasma": ["physics/plasma.js"],
    "impact": ["physics/impact.js"],
    "render": ["tools/render/render.js"],
    "agent-arena": ["brain/agent/arena.js", "brain/agent/arena-selfcheck.mjs"],
    "agent-pertick": ["brain/agent/arena.js", "brain/flowfieldCpu.js", "brain/agent/flow-selfcheck.mjs"],
    "fleet-agent": ["brain/agent/fleet.js", "brain/agent/fleet-selfcheck.mjs"],
    "trace-truth": ["tools/groundtruth/traceField.js"],
    "pulsar": ["physics/pulsar/pulsar.js"],
    "predict": ["physics/predict/predict.js"],
};
